### ISSUE TITLE
How setup Print css?

### ISSUE THREAD

**Issue by lucassmacedo** [CroudSupport/vue-fullcalendar#101]
I add in my app 
 @import "~assets/css/fullcalendar.print.css" print;
But appears not working

**Comment by BrockReece** [comment]
Hi, I'm afraid that I haven't tried this before, could it be an issue with the ordering of the imports?

**Comment by lucassmacedo** [comment]
is it possible, here it made no difference to put the css so, it is below the fullcalendar css
 @import '~fullcalendar/dist/fullcalendar.css'
@import "~assets/css/fullcalendar.print.css" print;

**Comment by BrockReece** [comment]
Ah ok, I will have a play when I have a bit of time, I'm not sure what would be causing this though, this is a transparent wrapper.

**Comment by lucassmacedo** [comment]
Ok, thanks bro.

**Comment by lucassmacedo** [comment]
@BrockReece Works if i add inside a fullcalendar.css @media print { full calendar css print here }.
If a include like i describe at the top, no works

**Comment by joshuacurtiss** [comment]
Any idea why `@import "/my/path/to/fullcalendar.print.css" print;` doesn't work?
