### ISSUE TITLE
Cannot read property 'calendar' of undefined

### ISSUE THREAD

**Issue by Lurgak** [CroudSupport/vue-fullcalendar#102]
I don't know if it's an Issue, or just my fault.
I am using vue-full-calendar 2.5.2 together with Scheduler 1.9.1.  
For creating an Event, i'm using modals, which works good. But when i pass the value back to calendar.vue to create the Event (console.log displays the created event), i'm getting this error:

main.js:94211 Uncaught TypeError: Cannot read property 'calendar' of undefined
    at Object.createEvent (main.js:94211)
    at VueComponent.createNewEvent (main.js:114600)
    at boundFn (main.js:5009)
    at invoker (main.js:6823)
    at HTMLButtonElement.fn._withTask.fn._withTask (main.js:6621)

```
// createEvent.vue -> Modal with input fields to create an Event
createNewEvent() {
     this.$modal.hide('create-event-modal');
     this.$parent.$options.methods.createEvent(this.event);
     this.event = {};
}
```

```
// calendar.vue
createEvent(newEvent) {
    console.log(newEvent);
    this.$refs.calendar.fireMethod('renderEvent', newEvent, true);
},
```

But if i create a event with an easier way, and pass the values to the same createEvent methode it shows no errors, and the event is rendered.
```
// calendar.vue
creatTestEvent() {
   const title = prompt('Event Title:');
   const resource = prompt('Resource Id:');

   let eventData;

   eventData = {
          title: title,
          start: this.selected.start,
          end: this.selected.end,
          resourceId: resource,
    };

   this.createEvent(eventData);
},
```

If it helps, I can attach the code

**Comment by BrockReece** [comment]
I think the scoping of `this` is incorrect when you try to invoke `this.$parent.$options.methods.createEvent(this.event)` from the modal.

If I were you, I would emit an event that the calendar.vue can listen to. Similar to this...

```
// createEvent.vue -> Modal with input fields to create an Event
createNewEvent() {
     this.$modal.hide('create-event-modal');
     this.$emit('create-event', this.event);
     this.event = {};
}
```
```
// calendar.vue template
<create-event @create-event="createEvent" />
```

I hope that helps?
Brock

**Comment by Lurgak** [comment]
Wow thank you very much, now it's working.

**Comment by BrockReece** [comment]
Awesome, happy to help.
