### ISSUE TITLE
In weekly view if any event is of two days then it will divide it from 12am.

### ISSUE THREAD

**Issue by palakdhingra** [CroudSupport/vue-fullcalendar#106]
In weekly view if any event is of two days then it will divide it from 12am, which makes user feel like its two different events, is there any way to fix it, need it very urgently :(

**Comment by BrockReece** [comment]
I feel like this is probably something you should raise on fullcalendar's github. This is just a wrapper for Vue.

**Comment by palakdhingra** [comment]
Ok thanks
