### ISSUE TITLE
Precise to add "window.jQuery = window.$ = require('jquery')" in the WEBPACK CONFIG

### ISSUE THREAD

**Issue by trollepierre** [CroudSupport/vue-fullcalendar#108]
Has mentioned in this issue (https://github.com/BrockReece/vue-fullcalendar-example/issues/5): you may have to precise to add in the  webpack config : https://github.com/BrockReece/vue-fullcalendar-example/blob/master/build/webpack.base.conf.js#L22

thanks

**Comment by BrockReece** [comment]
Hi @trollepierre,

I don't think you need to add jQuery to your project anymore, fullcalendar will do this for us if no jQuery  instance is detected.

I will update the readme later to reflect this.

**Comment by BrockReece** [comment]
@trollepierre See PR #110, does this look good to you?

**Comment by trollepierre** [comment]
Perfect!
