### ISSUE TITLE
Upgrade to fullcalendar 3.0

### ISSUE THREAD

**Issue by lucafaggianelli** [CroudSupport/vue-fullcalendar#13]
Any plan to upgrade fullcalendar 3.0? I would use it for the newly added 'list' views

**Comment by BrockReece** [comment]
Didn't even know there was a fullcalendar 3.0, thanks for the heads up.
Do you know if there are any breaking changes?

Cheers
Brock

**Comment by lucafaggianelli** [comment]
I read the changelog...and there is a dedicated section for breaking changes, but honestly I don't think that breaks your wrapper, probably just the internationalization option (lang) change and jQuery version change

https://github.com/fullcalendar/fullcalendar/blob/master/CHANGELOG.md#v300-2016-09-04

Luca

**Comment by BrockReece** [comment]
I have created a new branch for fullcalendar v3.
Let me know how you get on with it.

Cheers
Brock

**Comment by awdyer** [comment]
Working well for me. The new list views are great. Haven't noticed any other issues. Thanks for the update!

**Comment by BrockReece** [comment]
Cool, thanks. 

I have tagged and released a new minor version to NPM, 1.2.0
