### ISSUE TITLE
selectable and dayClick not working

### ISSUE THREAD

**Issue by fgzetech** [CroudSupport/vue-fullcalendar#139]
Hi, 
I'm trying to use the calendar en vue but I have some problems.
The events are not emitted.
<full-calendar :config="calendar.config" :events="calendar.events" @day-click="loadDay"></full-calendar>

loadDay function contains a console.log and it's not working.
selectable option and select event aren't working.

**Comment by DivingPigy** [comment]
With you. How to process it?

**Comment by BrockReece** [comment]
Hi, it looks like it is working for me in [code-sandbox](https://codesandbox.io/s/1zz00qvnzl)?

**Comment by DivingPigy** [comment]
Sir, how about select?

**Comment by DivingPigy** [comment]
Sir, how about select?
 I use the same method as your example in code-sandbox for day-click.
 But select event does not work.

**Comment by BrockReece** [comment]
`Selectable` is true by default and `event-created` is the event fired when an area of the graph is selected. You can always use the `config` prop to add callbacks to any of the fullcalendar events.

```js
config: {
  selectable: true,
  select: console.log,
}
```

**Comment by DivingPigy** [comment]
Sir, you mean define callback in the config, such as bellow:

`config: {
      selectable: true,
      select: "selectEvent"
}`
Is there any mistakes I made?

**Comment by BrockReece** [comment]
Sorry I was using a shorthand, I meant you define your callback in the config array, like so...

```js
config: {
  selectable: true,
  select() {
    // some logic
  },
}
```

**Comment by fgzetech** [comment]
I change the code. I removed de day-click event from the html and put it into de js file like this:
`calendar:{
            events: '',
            eventSources: [
                {
                    events(start, end, timezone, callback) {
                       //axios call
                    }
                }
            ],
            config: {
                defaultView: 'month',
                editable: false,
                //dayClick function is not working
                dayClick: function(date){
                    appConfig.calendar.selected = date;  
                },
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: ''
                },
                //this works well
                eventClick: function(event){
                    appConfig.calendar.selected = event;
                },
                locale: 'es'
            },
            selected: ''
        }`

**Comment by notchris** [comment]
I can also confirm @event-selected="eventSelected" does not get triggered on an event click as the documentation / examples suggest. Please provide a working example with the correct configuration when possible.

**Comment by BrockReece** [comment]
Hi @notchris 

I have added the `@event-selected` event handling to my example [codesandbox](https://codesandbox.io/s/52lwqnx18x). Clicking on the test event will write the event details to the log.

Does that make sense?

**Comment by notchris** [comment]
Thanks @BrockReece. I understand now!
