### ISSUE TITLE
Is listview surpported?

### ISSUE THREAD

**Issue by DivingPigy** [CroudSupport/vue-fullcalendar#143]
Official docs are written by Jquery, I can not translate the idea into vue.js. 
`<FullCalendar
:config="config">
</FullCalendar>

date(){
return {
config: {
defaultView: listView,
.......................
}
}
}`

Unfortunatly, It does not work.

**Comment by BrockReece** [comment]
I don't think `listView` is a valid view?
Shouldn't it be `listDay` || `listWeek` depending on what you want to show?

**Comment by BrockReece** [comment]
This is covered in fullcalendar's docs [here](https://fullcalendar.io/docs/list-view)
