### ISSUE TITLE
Any mechannism to get the this refrence in json-feed of full-calendar?

### ISSUE THREAD

**Issue by DivingPigy** [CroudSupport/vue-fullcalendar#149]
Hi!
        I am trying to get the this-reference of vue instance in json-feed. How ever a error show me that    "Error in mounted hook: "TypeError: this.axios is undefined" "  in browser console. What causes this? And how to fix it?

Code as bellow:
`events(start, end, timezone, callback) {
      this.axios.get(..............)  
        //do something here

        callback();
}`

**Comment by DivingPigy** [comment]
I define a that-refrence in created hook, then I use that.axios in json-feed object. However, I get the same error: "that.axios is undefined"

`created:{`
`//do something`
`let that =this;`
`}`

`eventsource:{`
`events(start , end , timezone , callback){`
`//do something`
`that.axios................`
`}`
`}`

**Result**: that.axios is undefined

**Comment by deanilvincent** [comment]
I'm using axios as well and it works fine with me.

First, I've imported the axios above

    import axios from "axios"

    data(){
       return{
           eventSources: [{
               events(start,end,timezone,callback){
                   axios.get(`/Something/`).then(response=>{
                       callback(response.data)
                   }).catch(error=>{console.log(error);});
               }
           }]
       }
    }

**Comment by DivingPigy** [comment]
I used this mechanism before. However my boss changed the software architecture, the axios has been changed to Global. Code as bellow:


import VueAxios from 'vue-axios';

Vue.use(VueAxios,axios)


Then, I program as bellow:
data(){    return{        eventSources: [{            events(start,end,timezone,callback){                this.axios.get(`/Something/`).then(response=>{                    callback(response.data)                }).catch(error=>{console.log(error);});            }        }]    } }
Result: this.axios is undefined.

 
 
------------------ Original ------------------
From: "Mark Deanil Vicente"; 
Date: 2018年7月26日(星期四) 中午1:58
To: "CroudTech/vue-fullcalendar"; 
Cc: "DivingPigy"<08123298@cumt.edu.cn>; "Author"; 
Subject: Re: [CroudTech/vue-fullcalendar] Any mechannism to get the thisrefrence in json-feed of full-calendar? (#149)

 

I'm using axios as well and it works fine with me.
 
First, I've imported the axios above
 import axios from "axios" data(){    return{        eventSources: [{            events(start,end,timezone,callback){                axios.get(`/Something/`).then(response=>{                    callback(response.data)                }).catch(error=>{console.log(error);});            }        }]    } }

**Comment by DivingPigy** [comment]
Oh!
     There is no this-reference in your sample code. Let me try once agian.

 
 
------------------ Original ------------------
From: "Mark Deanil Vicente"; 
Date: 2018年7月26日(星期四) 中午1:58
To: "CroudTech/vue-fullcalendar"; 
Cc: "DivingPigy"<08123298@cumt.edu.cn>; "Author"; 
Subject: Re: [CroudTech/vue-fullcalendar] Any mechannism to get the thisrefrence in json-feed of full-calendar? (#149)

 

I'm using axios as well and it works fine with me.
 
First, I've imported the axios above
 import axios from "axios" data(){    return{        eventSources: [{            events(start,end,timezone,callback){                axios.get(`/Something/`).then(response=>{                    callback(response.data)                }).catch(error=>{console.log(error);});            }        }]    } }

**Comment by DivingPigy** [comment]
Oh! Really works! Thank you sir!
 
 
------------------ Original ------------------
From: "Mark Deanil Vicente"; 
Date: 2018年7月26日(星期四) 中午1:58
To: "CroudTech/vue-fullcalendar"; 
Cc: "DivingPigy"<08123298@cumt.edu.cn>; "Author"; 
Subject: Re: [CroudTech/vue-fullcalendar] Any mechannism to get the thisrefrence in json-feed of full-calendar? (#149)

 

I'm using axios as well and it works fine with me.
 
First, I've imported the axios above
 import axios from "axios" data(){    return{        eventSources: [{            events(start,end,timezone,callback){                axios.get(`/Something/`).then(response=>{                    callback(response.data)                }).catch(error=>{console.log(error);});            }        }]    } }

**Comment by deanilvincent** [comment]
Oh I'm glad to know that. You're welcome :) @DivingPigy
