### ISSUE TITLE
Support for external draggable events?

### ISSUE THREAD

**Issue by Joakimpsd** [CroudSupport/vue-fullcalendar#16]
Thanks for a great wrapper!

Issue:
Doesn't work with external draggable events through jQuery UI, is this something that is on the roadplan? The eventDrop listener is only for event that are dragged from inside the cal, not triggering on external drop, the drop() method must be implemented in that case i believe? OR have i totally missed something? :D

**Comment by BrockReece** [comment]
Hi @Joakimpsd, thanks for your kind words

We have a 'get out of jail for free' config prop that you should be able to pass in extra listeners for times like this.

So I believe something like this should work....

```html
<full-calendar :events="events" :config="config"></full-calendar>
...
<script>
...
  data() {
    config: {
      droppable: true,
      drop(date) {
        alert("Dropped on " + date.format());
      },
    },
  },
...
</script>
```

Does that help?

Cheers
Brock

**Comment by Joakimpsd** [comment]
@BrockReece Thanks for swift reply.

I have indeed tested that, but it doesn't work, it seems like the calendar does not reply to being droppable at all (except for already in cal events), even tough i'm passing in
`droppable:true`

My entire config-object:
```javascript
calenderOptions: {
                    editable: true,
                    defaultView: 'month',
                    firstDay: 1,
                    timeFormat: 'HH:mm',
                    slotLabelFormat: 'HH:mm',
                    allDaySlot: false,
                    droppable: true,
                    drop(date) {
                        alert(date);
                    },
                    header: {
                        left:   'prev,next today',
                        center: 'title',
                        right:  'year,month,agendaWeek,agendaDay,listYear,listMonth'
                    },
                    views: {
                        listYear: {
                            buttonText: 'list year'
                        },
                        listMonth: {
                            buttonText: 'list month'
                        },
                    }
```

**Comment by BrockReece** [comment]
@Joakimpsd 

I haven't actually used the external drop feature on fullCalendar before and TBH this lib isn't doing anything other than wrapping fullCalendar.

[Reading around though](http://stackoverflow.com/questions/15782231/fullcalendar-drag-and-drop-not-working-on-my-website), someone suggests that you have to force the calendar to be droppable using with something like this
```js
$('#calendar').droppable();
```
Perhaps you could hack this to the end of the mounted method in your local copy of fullCalendar.vue and see if that works? If so I will look at a nicer way to integrate it.

Cheers
Brock
