### ISSUE TITLE
Dont make us require to use built in css

### ISSUE THREAD

**Issue by lukepolo** [CroudSupport/vue-fullcalendar#17]
In the component you require us to use their CSS

`<style src="../../fullcalendar/dist/fullcalendar.css"></style>`

Id rather allow the developer to include this themselves. As there are times when they do not want to inject the css directly into dom

**Comment by BrockReece** [comment]
That's a fair point.
It will be a breaking change for a lot of people though, how about adding a second component that doesn't include the css?

**Comment by lukepolo** [comment]
That works or release as a new major version #

**Comment by bbashy** [comment]
Would like this as well. Major version (if you follow semver) is perfect for this.

**Comment by BrockReece** [comment]
Ok, I will do that in the morning

**Comment by BrockReece** [comment]
Ok, this has now be changed in the latest Major release
https://github.com/CroudSupport/vue-fullcalendar/releases/tag/v2.0.0
