### ISSUE TITLE
How can you get the current date?

### ISSUE THREAD

**Issue by tspesh** [CroudSupport/vue-fullcalendar#181]
Not really an issue, so sorry but not sure where else to ask this.

I have a data structure that contains events that go back 3+ years and into the future at least a year.  This means thousands of records.  It would be vastly more efficient to make an API call for the current month's data only.  But I do not see a way to capture and then send the current month/year to make that request.

[FullCalendar has the getDate method](https://fullcalendar.io/docs/getDate).  How would I go about accessing that data in my component?

**Comment by BrockReece** [comment]
Hey, I would suggest looking at [this example](https://github.com/CroudTech/vue-fullcalendar#using-a-json-feed) in the readme. 

It uses the fullcalendar's [events (as a function)](https://fullcalendar.io/docs/events-function) where you can access the current date range as the first two arguments of the callback.

Hope that helps

**Comment by tspesh** [comment]
Thanks, so I saw that...but I'm not sure I understand it fully.

I need to pass the visible month back to my API.  How does this method do this? In my experimentation, i'm not able to pass any useful data to that events function.

**Comment by tspesh** [comment]
AH CRAP!

I wasn't paying attention completely...

What I needed
```js
<full-calendar :event-sources="eventSources"></full-calendar>
```

vs

What I had
```js
<full-calendar :events="eventSources"></full-calendar>
```
