### ISSUE TITLE
event render about timezone

### ISSUE THREAD

**Issue by yingchen518** [CroudSupport/vue-fullcalendar#189]
Hi,

I'm in Taiwan(+08:00). I set `events: [{ title  : 'event1', start  : '2019-03-13 08:00:00', end  : '2019-03-15 08:00:00', color: '#EB4D4D' }]`, but event render like the pic below.
![image](https://user-images.githubusercontent.com/25786199/54324408-9301ea80-4638-11e9-9243-460957d7469a.png)

I think it's a problem about timezone. I've tried pass 'timeZone' by using the config prop but it's not working. What should I do to pass 'timeZone'?

Thank you!

**Comment by BrockReece** [comment]
Can you format the start and end date to include timezone info?

**Comment by yingchen518** [comment]
Hi,

I tried
```
events: [
    {
        title: 'event1',
        start: '2019-03-10T08:00:00+08:00',
        end: '2019-03-13T08:00:00+08:00',
    },
    {
        title: 'event2',
        start: 'Sun Mar 10 2019 08:00:00 GMT+0800 (台北標準時間)',
        end: 'Sun Mar 13 2019 08:00:00 GMT+0800 (台北標準時間)',
    },
    {
        title: 'event3',
        start: new Date('2019-03-10T08:00:00+08:00'),
        end: new Date('2019-03-13T08:00:00+08:00'),
    },
    {
        title: 'event4',
        start: new Date('2019-03-10T08:00:00+08:00').toString(),
        end: new Date('2019-03-13T08:00:00+08:00').toString(),
    },
],
```
event2 and event4 can work! Thank you for your reply! :)

**Comment by BrockReece** [comment]
No problem.
