### ISSUE TITLE
end date is the day before the selected date

### ISSUE THREAD

**Issue by sunhuihuibuhui** [CroudSupport/vue-fullcalendar#199]
The version I'm using is "vue-full-calendar: ^2.7.0","vue-fullcalendar: ^1.0.9",
When I chose April 16th to 20th, the actual date was from 16th to 19th
I hope the selected end date is the same as the actual end date displayed
thank you~

**Comment by jstr14** [comment]
I have a similar error. When I display events on calendar end date displayed is one day less than end date. 

Any solution?

**Comment by sunhuihuibuhui** [comment]
> I have a similar error. When I display events on calendar end date displayed is one day less than end date.
> 
> Any solution?

no

**Comment by BrockReece** [comment]
Is it setting the end date's time to 00:00:00 so it appears like it stops a day early?

**Comment by jstr14** [comment]
I'm not setting the end date's time. I create my event like this:

```
{
title: 'name',
start: '2019-05-09',
end: '2019-05-10'
}
```

**Comment by BrockReece** [comment]
What if you add the `allDay: true` property?

**Comment by jstr14** [comment]
> What if you add the `allDay: true` property?

With allDay property it has same behaviour.

Edit: I try to add date like: YYYY-MM-DDTHH:mm:ss and use allDay:false, using this method event is displayed correctly but name displayed on event is like: `00:00 Event name` 

Is possible to avoid show hour on event displayed name?

**Comment by BrockReece** [comment]
Have you checked the docs of fullcalendar?

**Comment by jstr14** [comment]
> Have you checked the docs of fullcalendar?

Yes I check it. After read event-object docs I solve it adding one day to events that end date is not same day of start date.

https://fullcalendar.io/docs/event-object

> Date object that obeys the current timeZone. When your event ends. Could be null if you never specified an end.
> This value is exclusive! I repeat, this value is exclusive!!! An event with the end of 2018-09-03 will appear to span through the 2nd of the month, but will end before the start of the 3rd of the month.

After read this I think my solution is the best way to display events that duration is more than one day

**Comment by BrockReece** [comment]
Ah cool, thanks for doing the leg work on that.
