### ISSUE TITLE
Error in mounted hook

### ISSUE THREAD

**Issue by mickspecial** [CroudSupport/vue-fullcalendar#20]
I'm getting this error when I first transisition to a page

> Error in mounted hook: "TypeError: cal.fullCalendar is not a function"

Along with 

> cal.fullCalendar is not a function

But on page refresh it goes away and the calendar load and works as expected.

Thanks for any advice

**Comment by BrockReece** [comment]
Hi @mickspecial 
I have not seen this error before sorry.
Have you wrapped the component in a transition block?

**Comment by mickspecial** [comment]
Yes thats correct the page is being displayed within a transition following a redirection using the router.

```
<transition
mode="out-in"
enter-active-class="animated fadeInLeft" 
leave-active-class="animated fadeOutLeft">
<router-view></router-view>
</transition>
```

I ended up just using the standard full calendar as I wanted to use the [fullcalendar-scheduler](https://fullcalendar.io/scheduler/download/)

Hopefully you can resolve this bug and add in the scheduler as would much prefer to use your handy implementation.

Thanks

**Comment by BrockReece** [comment]
What do your animation classes look like?
I have just tested with a basic fade transition, with 'out-in' mode and it seemed to work.

It looks like that the scheduler module should work by just importing the scheduler.js file into the parent component, like....

```js
import 'fullcalendar-scheduler'
```

**Comment by mickspecial** [comment]
Hi,

I removed the animation effects so, my router has no transitions, and still getting the problem. 

Showing those errors on page load, but the cal appears once you refresh.

Tired everything I could think of to debug it - but no luck.

Where do you want me to import scheduler to ?

**Comment by BrockReece** [comment]
Oh cool, glad that you found a fix for this.
Does it work with the transitions again?

**Comment by mickspecial** [comment]
Yes, works perfect with animations.
