### ISSUE TITLE
Full Calendar Month View Issue

### ISSUE THREAD

**Issue by romil-officetroops** [CroudSupport/vue-fullcalendar#202]
Calendar is not showing 2 dates as selected if my end time is before 9AM.

For Ex: If start time is "2019-06-11 10:00:44" and end time is "2019-06-12 8:30:44" then in month view it marks only 11th not 12th. But it works fine in week view and day view. 

I have tried with above dates on https://codesandbox.io/s/5xlp873rkl but there also it does not mark 12th.

events: [
    {
       title: 'test',
       start: "2019-06-11T12:30:00",
       end: "2019-06-12T08:30:00",
     },
     {
	title: 'another test',
	start: ""2019-06-13T12:30:00"",
	end: "2019-06-14T09:30:00",
     }
  ],

**Comment by MiguelNepomuceno** [comment]
@romil-officetroops Have a look at this: https://fullcalendar.io/docs/nextDayThreshold
