### ISSUE TITLE
event.end is null when drap fullDay event drop to agenda.

### ISSUE THREAD

**Issue by ngooide** [CroudSupport/vue-fullcalendar#204]
Hi all pro,
When I drag a created allDay event drop into agendaWeek / agendaDay, I notice there is no event.end date assign to it. If this is not a bug, how to get the time frame is assign to current event?

Thank you!

![image](https://user-images.githubusercontent.com/4960528/61773077-58019600-ae26-11e9-95b7-55d4dc235938.png)

**Comment by BrockReece** [comment]
This feels like it would be more to do with the underlying behaviour of the fullcalendar lib, rather than this repo's plugin.

**Comment by ngooide** [comment]
ok. noted.

**Comment by ngooide** [comment]
I've done trick on this. Hope it help others.
event.end will add 2 hours into it when it drag from all-day to timeline.
```
eventDrop(event){
  if (event.allDay==false && !event.end){
    event.end = moment(event.start).add(2,'h');
  }
}
```
