### ISSUE TITLE
IE11,  npm run dev vue proect Error

### ISSUE THREAD

**Issue by liuliuboy** [CroudSupport/vue-fullcalendar#210]
"vue-full-calendar": "^2.6.1",
"webpack": "^4.41.2",
 "webpack-bundle-analyzer": "^3.5.2",
 "webpack-cli": "^3.3.9",
 "webpack-dev-server": "^3.8.1",
 "webpack-merge": "^4.2.2"

**Error: Missing semicolon**

![图片](https://user-images.githubusercontent.com/22977943/68568413-7a332880-0496-11ea-99b9-509fb0212eb8.png)

![1111](https://user-images.githubusercontent.com/22977943/68568488-a9e23080-0496-11ea-8e34-1321065f6320.jpg)

Thanks!

**Comment by BrockReece** [comment]
Do you use babel or any other transpiling tool?

**Comment by liuliuboy** [comment]
Yes, there is use, after troubleshooting, it has been fixed, thanks for reply；
webpack.base.conf.js
   {
        test: /\.js$/,
        loader: 'babel-loader?cacheDirectory=true',
        include: [
          resolve('src'), 
          resolve('test'), 
          resolve('node_modules/vue-full-calendar/components')
        ]
      }
