### ISSUE TITLE
Invalid after ‘daynames’ property is set

### ISSUE THREAD

**Issue by agnij** [CroudSupport/vue-fullcalendar#220]
After setting daynames:  ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'], the page still displays the default daynames of the locale:' zh CN '

**Comment by BrockReece** [comment]
How are you attempting to set the daynames?

**Comment by agnij** [comment]
> 您如何尝试设置日期名称？

I've done it. Thank you
