### ISSUE TITLE
Can i click on time labels.

### ISSUE THREAD

**Issue by eAvio** [CroudSupport/vue-fullcalendar#224]
Can somone help me. Is there an click event i can use to click on those labels? 

![image](https://user-images.githubusercontent.com/61407700/92726228-93825b00-f36d-11ea-8c91-a6e31dfcb39e.png)

(This issue is a question,)

**Comment by BrockReece** [comment]
I don't know off the top of my head, but here are the docs for the version of fullcalendar that this uses. 
https://fullcalendar.io/docs/v3#toc

**Comment by eAvio** [comment]
@BrockReece thank you for that, I could not find anything useful, for now im using vanilla JS, if anyone has a better solution feel free to comment, in case anyone will need the code ill add it here.

```
registerTimeClickEvent() {
      let tableRows = document.getElementsByTagName("tr");
      let section_id = this.$route.params.section_id;
      //for each found tr found
      tableRows.forEach((element) => {
        //get data time attribute, only the rows which have time labels use that attribute
        let dataTimeAttribute = element.getAttribute("data-time");
        if (dataTimeAttribute != null) {
          element.addEventListener("click", function () {
            //insert what click should trigger  
          });
        }
      });
}
```
