### ISSUE TITLE
Update events by next button

### ISSUE THREAD

**Issue by lucassmacedo** [CroudSupport/vue-fullcalendar#26]
Hello! How update events by next button? or prev, today, etc..

**Comment by BrockReece** [comment]
As in, how to load events based on the date range that you are currently looking at?
Something like [this?](https://fullcalendar.io/docs/event_data/events_function/)

**Comment by lucassmacedo** [comment]
Yes @BrockReece

**Comment by BrockReece** [comment]
Cool, I have an example app that uses the event function.

https://github.com/BrockReece/vue-fullcalendar-example/blob/master/src/App.vue
