### ISSUE TITLE
ChangeView

### ISSUE THREAD

**Issue by PT-EnfyS** [CroudSupport/vue-fullcalendar#31]
How can i change the view of full calendar? My default view is 'month', but i want to change to 'listYear' when i search for something on the calendar

**Comment by BrockReece** [comment]
There looks like there is a method that I don't believe our component exposes.
https://fullcalendar.io/docs/views/changeView/

I will try and create a generic method that will allow you to fire these into the fullcalendar instance and can be called like this...
```js 
this.$refs.calendar.fireMethod('changeView', 'agendaDay')
```
Would that work for you?

**Comment by PT-EnfyS** [comment]
Yes, i thing that will work. Thanks :smile:

**Comment by BrockReece** [comment]
Cool, so I have added this to v2.0.3

Let me know how you get on with it.
