### ISSUE TITLE
lodash noconflict?

### ISSUE THREAD

**Issue by mattcroftuk** [CroudSupport/vue-fullcalendar#32]
Is it possible that when lodash is imported that is set into no conflict mode?

I have other packages being included that are using underscore and it causing a bit of an issue for me as they keep treading on each other.

Or if someone can tell me if there is a way i can set it to no conflict etc without too much hassle.

Thanks.

**Comment by BrockReece** [comment]
I am actually now only using one module of lodash, I can totally just import that module instead of the entire lodash lib.

Sorry for my laziness, I will try and push a fix this afternoon.

**Comment by BrockReece** [comment]
In the latest version [2.0.4](https://github.com/CroudSupport/vue-fullcalendar/releases/tag/v2.0.4), Lodash has been trimmed down to only include the defaultsDeep module, so their should be no conflict over the usage of **_**

Cheers
Brock

**Comment by mattcroftuk** [comment]
Thanks very much for the quick turn around 👍

**Comment by BrockReece** [comment]
No problem, happy to help
