### ISSUE TITLE
Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by adavie1** [CroudSupport/vue-fullcalendar#34]
Hi,
I suspect this is a config issue- but I've followed the style of the example project. Despite that, still get this error.

My set up code is like this (in main.js):

`Vue.use(require('vue-full-calendar'))`

The usage, (in another component) is like this:

**HTML Section**:

```
<vue-full-calendar :events="selEvents" @eventClick="eventSelected">
</vue-full-calendar>

```
**Script Section**:

```
...
import VueFullCalendar from 'vue-full-calendar'

export default {
  components: {
    GeneralAction,
    VueFullCalendar
  },
...
```

BTW I've included the CSS import in App.vue - the main entry point.

Any pointers as to what I'm doing wrong would be great! :-)

**Comment by BrockReece** [comment]
Hi @adavie1,

You shouldn't need to import vue-full-calendar again in your component, this plugin adds the vue-full-calendar component globally. 

I have setup a [playground repo](https://github.com/BrockReece/vue-fullcalendar-example) as an example.

Cheers
Brock

**Comment by adavie1** [comment]
issue solved, details in the in issue on the [playground repo](https://github.com/BrockReece/vue-fullcalendar-example/issues/2).

**Comment by soaresdude** [comment]
I'm getting the same error. Already tried the solutions proposed here but without success.
Here's my code:
```vue
<template>
  <section class="section">
    <div class="field">
      <label class="label">Atividade</label>
      <div class="control">
        <div class="select">
          <select v-model="product" @change="loadCalendar">
            <option :value="null">Selecione um produto</option>
            <option v-for="product in  allProducts" :value="product.id" :key="product.id">
              {{ product }}
            </option>
          </select>
        </div>
      </div>
    </div>
    <div class="control">
      <full-calendar :events="events"></full-calendar>
    </div>
  </section>
</template>

<script>
  import FullCalendar from 'vue-full-calendar'

  export default {
    data() {
      return {
        product: null,
        events: [
          {
            title: 'event1',
            start: '2010-01-01'
          },
          {
            title: 'event2',
            start: '2010-01-05',
            end: '2010-01-07'
          },
          {
            title: 'event3',
            start: '2010-01-09T12:30:00',
            allDay: false
          }
        ]
      }
    },
    components: {
      FullCalendar
    },
    created () {
      //
    },
    computed: {
      allProducts() {
        return this.$store.state.product.allBySeller
      }
    },
    methods: {
      loadCalendar () {
        //
      }
    }
  }
</script>

<style scoped>

</style>
```

webpack:
```javascript
plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery'
    })
]
```

**Comment by BrockReece** [comment]
Your import statement is wrong. You are importing the Vue plugin rather than the component. Try the following import statement.

```
import { FullCalendar } from 'vue-full-calendar'
```

**Comment by soaresdude** [comment]
Thanks, but now it's like this:
![image](https://user-images.githubusercontent.com/3741554/54464847-22052480-4757-11e9-85b2-037ec84a3411.png)

**Comment by PhilMDev** [comment]
Your dates are in 2010. The calendar starts last Sunday March 10, 2019. Try
changing your test dates.

Also I'm not positive since I'm at my phone instead of my computer but I
think you need end dates also.

**Comment by soaresdude** [comment]
@PhilMDev I've left only 
```javascript
{
            title: 'event2',
            start: '2019-03-15',
            end: '2019-03-18'
          }
```
and the problem persists.

**Comment by soaresdude** [comment]
I had to import the `fullcalendar.min.css`. Now it seems fine, thanks for the help guys :)
