### ISSUE TITLE
Best way to customize events in eventRender

### ISSUE THREAD

**Issue by smingam** [CroudSupport/vue-fullcalendar#35]
Hello everyone, I'm looking at the customization possibilites of events, and I'm wondering what would be a 'good' way.

As I found in issue #25 , I'm appending some html to the jquery element, but that's rather crude:

```javascript
'eventRender' (event, element, view) {
    element.append(
        '<div class="event-details">' +
        '<div class="client">' + event.data.project.client + '<div>' +
        '<div class="user">' + event.data.task.user.name + ' @ ' + event.data.task.studio + '<div>' +
        '</div >'
    )
}
```
Is there a better way? Like, more vue-like (kinda, 'server-side' rendering of a component?), or something with templates at least?

Thanks a lot!
Steve

**Comment by BrockReece** [comment]
I doubt you would be able do anything too clever here as fullcalender isn't Vue aware.

I have just had a play round with the Vue createElement method but it looks like it returns a vnode and not a html string so I don't think that would be of use here.

**Comment by steven87vt** [comment]
Maybe take a look at the examples on fullcalendar.io about tooltip:

[https://fullcalendar.io/docs/event-tooltip-demo](https://fullcalendar.io/docs/event-tooltip-demo)

The example basically shows that you can embed metadata as html into the single event the way you are doing it with eventRender:

```
eventRender: function(eventObj, $el) {
 $el.popover({
     title: eventObj.title,
     content: eventObj.description,
     trigger: 'hover',
     placement: 'top',
     container: 'body'
 );
}
```

Or in bootstrap: [bootstrap tooltips & fullcalendar.io](https://stackoverflow.com/questions/18633687/twitter-bootstrap-tooltips-do-not-work-for-events-in-fullcalendar)
```
eventAfterRender: function (event, element) {
  $(element).tooltip({title:event.title, container: "body"});
}
```
