### ISSUE TITLE
How do I get navLinks working in vue-fullcalendar?

### ISSUE THREAD

**Issue by randymoss94** [CroudSupport/vue-fullcalendar#36]
I would like to set navLinks: true in fullcalendar, how do I do that in vue-fullcalendar?

**Comment by BrockReece** [comment]
Hi @randymoss94,

You can use the **config** prop to pass additional settings to fullcalendar, something like this should work...
```html
<full-calendar :config="{navLinks: true}" />
```

Cheers
Brock

**Comment by randymoss94** [comment]
awesome it works perfectly thank you Brock

**Comment by BrockReece** [comment]
No problem 😄
