### ISSUE TITLE
Events are duplicating after changing month

### ISSUE THREAD

**Issue by bbashy** [CroudSupport/vue-fullcalendar#38]
Having some trouble after using your solution in issue #37 

After each site change, the events change (from JSON API) but clicking on next month makes the events duplicate based on the count of the site changes (times selected).

Here's a GIF of what's happening: https://d.pr/i/7B1eT/4KXGH5Wh

**Comment by BrockReece** [comment]
Hi again,

What does your code look like? specifically what props are you passing through to full-calendar?

**Comment by bbashy** [comment]
Hey :P

It's basically just a v-model select with the code from the other issue and this for pulling in the calendar;
```html
<full-calendar ref="calendar" :event-sources="events" :config="config"></full-calendar>
```

**Comment by BrockReece** [comment]
Ok, does this suggest that we don't need to update the eventSources at all, as it is already dynamically grabbing your ``site`` val correctly in the duplicated api calls?

Could we just fire in the **refetchEventSources** method when that dropdown val changes?

```js
this.$refs.calendar.fireMethod('refetchEventSources')
```

**Comment by bbashy** [comment]
Having trouble executing that
```
Error in render function: "TypeError: this.$refs.calendar.fireMethod is not a function"
```

**Comment by BrockReece** [comment]
Are you using the latest version of vue-full-calender, it is a recent addition.

**Comment by bbashy** [comment]
Ah, two minor versions behind! Right, that's not erroring now.

I've just checked the network tab and it's calling the API multiple times for the last selected site ID.

1. Select site 1
2. Calendar loads with site 1 from the API
3. Select site 2
2. Calendar loads with site 2 from the API
4. Change month and network tab shows 2 API requests to site 2

**Comment by bbashy** [comment]
Thanks for the help. Adding it to the data section just loads `/api/events/` since there's no site selected then obviously changing the site doesn't change the API call.

**Comment by BrockReece** [comment]
Sorry I should have been more verbose with my last message, my suggestion was a combination of all of the above and to get round the api call with no site information, you can add an early return to the events source handler.

The irony of this being where you started from is not lost on me.

```html
<select v-model="site" @input="siteChanged">
...
</select>
```

```js
data() {
   $this = this
   return {
        site: null,
        eventSources: [
            {
                events(start, end, timezone, callback) {
                    if (!$this.site) {
                        callback(response.data.data)
                        return
                    }

                    axios.get(`/api/events/${$this.site}`).then(response => {
                        callback(response.data.data)
                    })
                },
            },
        ],
    }
},

methods: {
    siteChanged() {
        this.$refs.calendar.fireMethod('refetchEventSources')
    }
}
```

**Comment by bbashy** [comment]
I see!

Got the method for changing site (reaches) but the following line inside that doesn't seem to activate the API call in `data()`?

```
this.$refs.calendar.fireMethod('refetchEventSources')
```

**Comment by BrockReece** [comment]
Can you put a `console.log()` above the `if (!$this.site) {` to see if that callback is being ran?
You may have to manage when the method gets fired, like this...

```js
this.$nextTick(() => {
    this.$refs.calendar.fireMethod('refetchEventSources')
})
```

**Comment by BrockReece** [comment]
Sorry, I totally had the wrong refetch method for fullcalendar
This worked in my test
```js
    mounted() {
        setTimeout(() => {
            this.site = 'another'
            this.$refs.calendar.fireMethod('refetchEvents')
        }, 1000)
    },
```

**Comment by BrockReece** [comment]
```js
export default {
    data() {
        const $this = this
        return {
            site: 'test',
            eventSources: [
                {
                    events(start, end, timezone, callback) {
                        console.log($this.site)
                        callback([])
                    },
                },
            ],
        }
    },

    mounted() {
        setTimeout(() => {
            this.site = 'another'
            this.$refs.calendar.fireMethod('refetchEvents')
        }, 1000)
    },
}
```
outputs...
```js
test
another
```

**Comment by bbashy** [comment]
Okay, now we have something!

This is now refetching the events and they aren't duplicated on month change.
```
siteChanged() {
    this.$nextTick(() => {
        this.$refs.calendar.fireMethod('refetchEvents')
    })
},
```

Thanks!

_Is it right that I can't seem to use `$this = this`? Had to use `let $this = this`_

**Comment by BrockReece** [comment]
Awesome, sorry about the huge detour.
Yeah totally, I was just being lazy, I would personally use `const $this = this`

**Comment by bbashy** [comment]
Thanks a lot though, learned a lot and I thought so :)

❤️
