### ISSUE TITLE
Events not updating

### ISSUE THREAD

**Issue by randymoss94** [CroudSupport/vue-fullcalendar#39]
Inside of  my calendar.vue component I have a fullcalendar component. 
Within calendar.vue I have a method called submit. Inside of submit I make a 
(successful) reference to the fullcalendar component with 
"this.$refs.calendar". However when I do 
"this.$refs.calendar.$emit('refetchEvents');" in my submit function the 
events are not fetched (my events are not updated on my calendar). Why 
are my events not being updated upon submit and how can I update them?

The (relevant) code for the calendar.vue component can be found here:
https://github.com/randymoss94/calendar.vue/blob/master/eventQuestion.vue

and the full project can be found here:
https://github.com/randymoss94/schedulerCurrent

**Comment by randymoss94** [comment]
also this.$refs.calendar.$emit('refetch-events'); does not work either

**Comment by randymoss94** [comment]
also lets say that the id property in the data section of calendar.vue changes and I want to have eventSources update based on the new id. For example my server will send back a different set of events based on the new id sent to it by calendar.vue. So how to I get calendar.vue to update my events when the value of my id changes?

**Comment by BrockReece** [comment]
Hi @randymoss94,

I think the scoping is wrong on your event sources, I think ``this`` will resolve to the fullcalendar instance, so I am not sure ``this.$store.getters.user`` will ever evaluate correctly.

Are you getting any errors in your console , or is it making correct network requests?

Once you have sorted that out, I think you should be able to refetch events using this command...

```js
this.$refs.calendar.fireMethod('refetchEventSources')
```

**Comment by randymoss94** [comment]
When I put "this.$refs.calendar.fireMethod('refetchEvents')" inside of my submit function I get this error:
"Uncaught TypeError: this.$refs.calendar.fireMethod is not a function
    at VueComponent.submit "
However when I click on an arrow button to change the week I've notice that the events are fetched so perhaps if there is a way to see what functions are triggered when the arrow button is clicked that could solve my problem but I could'nt figure that out. Otherwise If we could get "this.$refs.calendar.fireMethod('refetchEvents')"  working that would solve my problem as well. I have updated the code here to reflect its current state : https://github.com/randymoss94/calendar.vue/blob/master/eventQuestion.vue

**Comment by BrockReece** [comment]
Hey, so you may be a few minor versions behind, as that method was
something I added last week. And that is basically what fullcalendar runs
when you switch between weeks.

Cheers
Brock

**Comment by randymoss94** [comment]
How do I update to the current version?

**Comment by BrockReece** [comment]
You can upgrade using your package manager. 

If you are using NPM 
``` 
npm update vue-full-calendar`
```

Or if you are using Yarn
```
yarn upgrade vue-full-calendar
```

**Comment by randymoss94** [comment]
awesome I'll try that

**Comment by randymoss94** [comment]
Ok so I think we are getting closer, I have updated my version and I believe "refetch events" is now working. However when I press submit nothing happens but when I hit submit a second time (to create another event) the previous event is rendered to the screen. I am wondering if perhaps because I am making a post request from my submit function that it would somehow prevent my newly submitted event from being rendered to the screen. Again the event I create once submit is pressed is only rendered to the screen the second time that the submit button is pressed. Here is the relevant code I tried to comment it the best I could to give you a clearer picture of what's going on https://github.com/randymoss94/calendar.vue/blob/master/eventQuestion.vue

**Comment by BrockReece** [comment]
Yep you are almost there, `this.$http.post` is an async method so it is firing the refresh before the post is complete. If you move the refresh to where the promise is resolved, you can guarantee it will be ran after the new event has been created.

This should work for you...

```js
this.$http.post('http://localhost:3000/operation?Stime='+this.Stime+'&Etime='+this.Etime+'&eAMPM='+this.eAMPM+'&sAMPM='+this.sAMPM+'&id='+this.id+'&activity='+this.activity+'&auto_insert='+this.auto_insert+'&yearmonthday='+this.yearmonthday+'&color1='+this.c+'')
      .then(response => {
        //handle response
        this.response = response.body;
        this.$refs.calendar.fireMethod('refetchEvents')
      })

**Comment by randymoss94** [comment]
I think that did the trick! Thank you Brock!!

**Comment by BrockReece** [comment]
Awesome :)
