### ISSUE TITLE
Support vue2

### ISSUE THREAD

**Issue by silvestreh** [CroudSupport/vue-fullcalendar#4]
This library doesn't seem to be compatible with Vue 2.x 😢

**Comment by BrockReece** [comment]
It isn't yet. I will look into it though.

Cheers
Brock

**Comment by BrockReece** [comment]
I have merged in a pull request by @fishr01 and also bumped the major version of the NPM package to 1.0.0 due to the breaking changes

Vue 1.x users can still use @0.0.3
