### ISSUE TITLE
Problem with Router

### ISSUE THREAD

**Issue by lucassmacedo** [CroudSupport/vue-fullcalendar#40]
Hello Guys! I have a problem when i redirect to another page and back to page with calendar.. all events stop working.. 
Im using vue-router 
It seems that the emit does not arrive until the event
```
<router-link :to="{ name: 'home' }">Home</router-link>
<router-link :to="{ name: 'calendar' }">Calendar</router-link>
```

**Comment by BrockReece** [comment]
Hi @lucassmacedo,

What do you mean by all events stop working? Vue component events aren't emitting or the Calendar events aren't showing?

I have not tested with Vue router, I will fire up a quick Vue project now and test.

Cheers
Brock

**Comment by lucassmacedo** [comment]
Example:  i have my component to page /calendar
`
  | <template>
  | 
  | <div class="full-width">
  | <full-calendar ref="calendar" :config="account.days"
  | @event-created="eventCreated"
  | >
  | </full-calendar>
  | </div>
  | </template>
  |  
  | <script type="text/javascript">
  | import {mapMutations, mapGetters} from 'vuex'
  |  
  | import calendarService from '@/services/calendar.service';
  |  
  | export default{
  |......
  | methods: {
  | eventCreated(event) {
  | alert(event)
  | },
  | }
  | }
  | </script>
`
the first time when i enter in route works fine, but i click to /home in menu, and back to /calendar, stop working the method eventCreated, i not receive more the emit ..

**Comment by BrockReece** [comment]
That is odd.

I built a vue-router application this morning and the emits were working for me when I was travelling through the pages.

Do you have anything special set up on the router?

**Comment by lucassmacedo** [comment]
No.. 
import Vue from 'vue'
import VueRouter from 'vue-router'


```
Vue.use(VueRouter)

const routes = [
  {
    path: '/',
    name: 'home',
    components: {
      default: require('pages/home'),
      menuView: require('components/leftSlide')
    },
    meta: {
      title: "Dashboard",
      auth: true
    }
  },
  {
    path: '/calendar',
    name: 'calendar',
    components: {
      default: require('pages/calendar'),
      menuView: require('components/leftSlide')
    },
    meta: {
      title: "Calendar",
      auth: true
    }
  }
]


const router = new VueRouter({
  routes,
  mode: 'history', //default: hash ,history
})

export default router
```
In main.js
```import './config';

import Vue from 'vue'

import App from './App'

import router from './router'

import store from './store'

import { sync } from 'vuex-router-sync'

Vue.config.productionTip = true


sync(store, router)

new Vue({
  router,
  store,
  ...App
}).$mount('app')
 ```

**Comment by lucassmacedo** [comment]
In devtools > evets, are working.. when i click the event Is being fired, but the method  not receive

**Comment by BrockReece** [comment]
What does the Component lifecycle look like in vue-router? does it tear it down when not currently visible or is it kept alive?

**Comment by lucassmacedo** [comment]
I want kept alive, but he is destroyed when a leave the page..

**Comment by BrockReece** [comment]
do you have the `<keep-alive>` tags around the router-view?

https://router.vuejs.org/en/api/router-view.html

**Comment by lucassmacedo** [comment]
Thanks @BrockReece !! I add the <keep-alive> around router-view and are works fine! Sorry for the mess

**Comment by BrockReece** [comment]
No problem, glad I could help. I really need to have a closer look at vue-router sometime.

**Comment by lucassmacedo** [comment]
Hello @BrockReece i find a a Root  problem.. is [her](https://github.com/CroudSupport/vue-fullcalendar/blob/master/components/FullCalendar.vue#L161) when a set a config by the prop the problem showing. If i set a manualy config not showing anymore.. i remove the <keep-alive> and works fine if i remove the prop config and add manualy one by one.. 
my config was 
`{ "defaultView": "agendaWeek", "minTime": "08:00", "maxTime": "18:00", "slotLabelInterval": "00:30:00", "slotDuration": "00:30:00", "hiddenDays": [ 0 ], "businessHours": [ { "start": "08:00", "end": "12:00" }, { "start": "14:00", "end": "18:00" } ] }`

**Comment by BrockReece** [comment]
Does your code snippet work?
I'm not sure why you are having difficulties passing the config prop through, are their any errors in the console?

**Comment by lucassmacedo** [comment]
Yes, work perfectly, but when change route and back the events stops working, when i remove the config, and set manually, works fine when a change the route the events works fine to. Have no errors on console

**Comment by lucassmacedo** [comment]
I pass the values from vuex, to :config

**Comment by skout90** [comment]
@BrockReece  Thanks!!
