### ISSUE TITLE
eventDrop not always keeping moved items when switching months (no refresh)

### ISSUE THREAD

**Issue by bbashy** [CroudSupport/vue-fullcalendar#43]
Sometimes the events that have been moved, reset after changing months and then going back.

Is there anything special I need to do to make sure they update and not reset?
```
eventDrop: (event, delta, revertFunc) => {
    console.log(event.title + " was dropped on " + event.start.format());

    self.$refs.calendar.$emit('event-drop', event, delta, revertFunc);
},
```

**Comment by BrockReece** [comment]
How are you passing events through to your calendar?

**Comment by bbashy** [comment]
eventSources within data()
```
eventSources: [
    {
        events(start, end, timezone, callback) {
            if (! self.site) {
                callback([])
                return
            }

            axios.get(`/api/events/${self.site}`).then(response => {
                callback(response.data.data)
            })
        },
    },
],
```

**Comment by BrockReece** [comment]
So everytime you change your view it will be running that `events` method.

Unless you are persisting the new event drop to your API you will lose your changes every time you move away from the current view.

...unless I am missing the point?

**Comment by bbashy** [comment]
Okay makes sense. Sometimes it doesn't do a request though. I haven't implemented the saving of the new date but was just testing before I did it.

Seems to be when switching to `agendaWeek` and `listYear` and back to `month`.

**Comment by BrockReece** [comment]
I am guessing if it wouldn't need to make additional requests if the new view is a subset of the data it has already loaded, but I am pretty certain it makes a new request everytime you expand or move the current date window.

Glad it is working for you now, though.

Cheers
Brock
