### ISSUE TITLE
Multiple Event Sources Only Using First

### ISSUE THREAD

**Issue by noynek** [CroudSupport/vue-fullcalendar#46]
I've got two eventSources: a JSON feed and a function that returns events. The problem is that only the first eventSource is getting called. Am I missing something?

        data: function () {
            var self = this;
            return {
                eventSources: [{
                    events: function (start, end, timezone, callback) {
                        var events = getEvents(start, end, timezone);
                        callback(events)
                    },
                    events: function (start, end, timezone, callback) {
                        self.$http.get('//myjsonfeed', {
                            params: {
                                start: start.format(),
                                end: end.format()
                            }
                        }).then(function (response) {
                            callback(response.data);
                        });
                    }
                }],`

**Comment by BrockReece** [comment]
Hi @noynek,

Your eventSources array isn't formatted properly, your event functions are part of the same object and thus overridden. They should be in separate objects, like so...

```js
        eventSources: [
            {
                events: function (start, end, timezone, callback) {
                    var events = getEvents(start, end, timezone);
                    callback(events)
                },
            },
            {
                events: function (start, end, timezone, callback) {
                    self.$http.get('//myjsonfeed', {
                        params: {
                            start: start.format(),
                            end: end.format()
                        }
                    }).then(function (response) {
                        callback(response.data);
                    });
                }
            }
       ],`
```

Hope that helps.
Brock

**Comment by noynek** [comment]
Got it! Thanks for clarifying, Brock.
