### ISSUE TITLE
eventResized Assigning Event Object

### ISSUE THREAD

**Issue by noynek** [CroudSupport/vue-fullcalendar#47]
First off, huge thank you for building and maintaining this and being so responsive. Here's an issue I can't figure out. 

When a user resizes an event, I want to show a modal where they can edit some of the event info and confirm their change.

I'm using the following to set a `selectedEvent` property. It appears to work, but if you resize a second or third time, you can see that the dragging behavior breaks. 

    eventResized: function(event) {
        //this is where the problem happens'
        this.selectedEvent = event;
    }

I did an additional test of assigning to an outside variable and it doesn't cause the same problem.

    var selectedEvent;

    eventResized: function(event) {
        //no problem here, but the event data is no longer in the Vue scope.
        selectedEvent = event;
    }

Here's a codepen showing the behavior. Any suggestions?
https://codepen.io/noynek/pen/OjjWeY

**Comment by BrockReece** [comment]
Hmm... looks like a reactivity issue.
If you wrap the event in a [deep clone](https://lodash.com/docs/4.17.4#cloneDeep) before assigning it to `this.selectedEvent`, it seems to fix the issue.

```js
eventResized: function(event) {
    // clone deep will remove the reactivity.
    this.selectedEvent = _.cloneDeep(event);
}
```
Working example
https://codepen.io/BrockReece/pen/gxxxPJ?editors=1111

**Comment by noynek** [comment]
Great, cloneDeep seems to work in my brief testing. I'm wondering if this is just a best practice. Thank you very much, Brock.

**Comment by BrockReece** [comment]
I agree, it feels a bit hacky.
I will experiment with fixing it at the component level.

Glad it is working for you though 👍
