### ISSUE TITLE
I am having issues refreshing events when I add a new one

### ISSUE THREAD

**Issue by chevoldavis** [CroudSupport/vue-fullcalendar#48]
Here is some code to better illustrate what I am doing (err, trying to do): 
```
<template>
<div>
    <full-calendar ref="calendar" :event-sources="eventSources"  @day-click="daySelected" @event-selected="eventSelected" :config="config"></full-calendar>

    <!-- Modal Component -->
    <b-modal ref="my_modal" title="New Appointment" @ok="submit" @shown="clearModalValues">
      <form @submit.stop.prevent="submit">
        <label>Client:</label>
        <b-form-select v-model="selectedClient" :options="clientOptions" class='mb-3'></b-form-select>

        <label>Service:</label>
        <b-form-select multiple v-model="selectedService" :options="serviceOptions" class='mb-3'></b-form-select>

        <label>Start time:</label>
        <time-picker v-model="myTime"></time-picker>

        <label>Notes:</label>
        <b-form-input textarea v-model="notes" placeholder="Notes"></b-form-input>
      </form>
    </b-modal>
    <!-- /Modal Component -->

  </div>
</template>

<script>
export default {
  props: {
    staff:{
      type: Number,
      required: true
    },
  },
  data() {
    return {
      myTime: new Date(),
      selectedService: [null],
      selectedClient: null,
      selectedStartTime: new Date(),
      notes: null,
      serviceOptions: [],
      clientOptions: [],
      events: [],
      config: {
        timeFormat: 'h(:mm)',
        eventClick: (event) => {
          console.log('Event Clicked: '+event.title);
        },
      },
      selected: {},
    };
  },
  computed: {
    eventSources() {
      return [
        {
          events(start, end, timezone, callback) {
            axios.get('/getEvents').then(response => {
              callback(response.data)
            })
          }
        }
      ]
    }
  },
  mounted() {
    this.myTime = new Date()
    axios.get('/getClients').then(response => this.clientOptions = response.data);
    axios.get('/getServices').then(response => this.serviceOptions = response.data);
  },
  methods: {
    clearModalValues() {
      this.selectedService = [null];
      this.selectedClient = null;
      this.selectedStartTime = new Date();
      this.myTime = new Date();
      this.notes = null;
    },
    submit(e) {
 
      axios.post('/addEvent/',{'selectedService':this.selectedService,'selectedClient':this.selectedClient,'selectedStartTime':this.selectedStartTime,'notes':this.notes}).then(function(response){
        //console.log(response.data);
        new PNotify({
          title: 'Success',
          text: 'New event has been created',
          icon: 'icon-checkmark3',
          type: 'success'
        });

        this.selectedService = [null];
        this.selectedClient = null;
        this.selectedStartTime = new Date();
        this.notes = null;
        this.myTime = new Date();

       // ******** I HAVE TRIED THESE CALLS AS PER DOCUMENTATION **********
       //this.$refs.calendar.fireMethod('refetch-events')
        //this.$refs.calendar.fullCalendar.$emit('refetch-events');
        //this.$refs.calendar.$emit('refetch-events');

        console.log(this.$refs.calendar);
      }.bind(this));
    },
    eventSelected(event) {
      console.log('Event Selected: '+event.title);
    },
    daySelected(date,event,view){
      this.$refs.my_modal.show();
      this.selectedStartTime = date.format("YYYY-MM-DD HH:mm:ss");
      this.myTime = date.toDate();
    },
  },
};
</script>

```

I keep getting errors when I try and call refresh-events. Events are there on load but when I add a new one I cannot get the data to refresh or to call eventSources to refetch the events. Any help would be greatly appreciate!

**Comment by chevoldavis** [comment]
Looking at the docs and examples, I should be able to call 
`this.$refs.calendar.$emit('refetch-events');`

and it  

> Makes another JSON call to event sources

**Comment by BrockReece** [comment]
Hi @chevoldavis 

What are the errors you see when you try and call refresh-events?
And what does the line `console.log(this.$refs.calendar);` print out?

**Comment by chevoldavis** [comment]
Hey Brock, thanks for the response. The error I am getting when calling this.$refs.calendar.$emit('refetch-events'); is this:
`[Vue warn]: Error in event handler for "refetch-events": "TypeError: $(...).fullCalendar is not a function"`

console.log(this.$refs.calendar); prints out:
`VueComponent {_uid: 2, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}$attrs: (...)$children: []$createElement: ƒ (a, b, c, d)$el: div#calendar.fc.fc-unthemed.fc-ltr$listeners: (...)$options: {parent: VueComponent, propsData: {…}, _parentVnode: VNode, _parentListeners: {…}, _renderChildren: undefined, …}$parent: VueComponent {_uid: 1, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}$refs: {calendar: div#calendar.fc.fc-unthemed.fc-ltr}$root: Vue$3 {_uid: 0, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: Vue$3, …}$scopedSlots: {}$slots: {}$validator: Validator {strict: true, fields: FieldBag, paused: false, …}$vnode: VNode {tag: "vue-component-54-full-calendar", data: {…}, children: undefined, text: undefined, elm: div#calendar.fc.fc-unthemed.fc-ltr, …}config: (...)defaultConfig: (...)defaultView: (...)editable: (...)errors: (...)eventSources: (...)events: (...)fields: (...)fireMethod: ƒ boundFn(a)header: (...)selectHelper: (...)selectable: (...)sync: (...)_c: ƒ (a, b, c, d)_computedWatchers: {defaultConfig: Watcher, errors: Watcher, fields: Watcher}_data: {__ob__: Observer}_directInactive: false_events: day-click: [ƒ]event-selected: [ƒ]rebuild-sources: [ƒ]refetch-events: [ƒ]reload-events: [ƒ]remove-event: [ƒ]render-event: [ƒ]rerender-events: [ƒ]_hasHookEvent: false_inactive: null_isBeingDestroyed: false_isDestroyed: false_isMounted: true_isVue: true_props: {…}_provided: {$validator: Validator}_renderProxy: Proxy {_uid: 2, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}_self: VueComponent {_uid: 2, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}_staticTrees: []_uid: 2_vnode: VNode {tag: "div", data: {…}, children: undefined, text: undefined, elm: div#calendar.fc.fc-unthemed.fc-ltr, …}_watcher: Watcher {vm: VueComponent, sync: false, lazy: false, user: false, deep: false, …}_watchers: (6) [Watcher, Watcher, Watcher, Watcher, Watcher, Watcher]$data: (...)$isServer: (...)$props: (...)$ssrContext: (...)get $attrs: ƒ reactiveGetter()set $attrs: ƒ reactiveSetter(newVal)get $listeners: ƒ reactiveGetter()set $listeners: ƒ reactiveSetter(newVal)get errors: ƒ computedGetter()set errors: ƒ ()get fields: ƒ computedGetter()set fields: ƒ ()__proto__: Vue$3
`

**Comment by BrockReece** [comment]
Ah, I have seen the `TypeError: $(...).fullCalendar is not a function` error before and it is usually down to an issue with multiple versions of fullcalendar being in play at the same time.

Could you tell me a bit about your setup...
Are you using webpack?
NPM or yarn?
Versions of fullcalendar and vue-full-calendar in your package.json?

**Comment by chevoldavis** [comment]
Sure, I am using it in a Laravel website. Its using NPM, here are the versions I'm using:
```
    "axios": "^0.16.2",
    "bootstrap-vue": "^0.22.1",
    "fullcalendar": "^3.4.0",
    "uiv": "^0.11.8",
    "vee-validate": "^2.0.0-rc.13",
    "vue": "^2.4.2",
    "vue-full-calendar": "^2.0.6"
```

**Comment by BrockReece** [comment]
As vue-full-calendar has fullcalendar as a dependency, could you try removing it from your project?

**Comment by chevoldavis** [comment]
When running npm run dev, I now get an error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.10.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 silly lifecycle @~predev: no script for predev, continuing
7 info lifecycle @~dev: @
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Library/WebServer/Documents/SalonSexy/node_modules/.bin:/Users/the_gh0st/Library/Android/sdk//tools:/Users/the_gh0st/Library/Android/sdk//platform-tools:/Users/the_gh0st/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/the_gh0st/Library/Android/sdk//tools:/Users/the_gh0st/Library/Android/sdk//platform-tools:/Users/the_gh0st/.composer/vendor/bin
10 verbose lifecycle @~dev: CWD: /Library/WebServer/Documents/SalonSexy
11 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
12 silly lifecycle @~dev: Returned: code: 2  signal: null
13 info lifecycle @~dev: Failed to exec dev script
14 verbose stack Error: @ dev: `npm run development`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /Library/WebServer/Documents/SalonSexy
17 error Darwin 16.4.0
18 error argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error @ dev: `npm run development`
23 error Exit status 2
24 error Failed at the @ dev script 'npm run development'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the  package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run development
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]
```

**Comment by chevoldavis** [comment]
I re-ran npm install vue-full-calendar and then ran npm run dev and it ran fine. However I am still getting the following error on the page:
`[Vue warn]: Error in event handler for "refetch-events": "TypeError: $(...).fullCalendar is not a function"`

**Comment by BrockReece** [comment]
Ah maybe I am miss-remembering, do you have 2 versions of jQuery running?

**Comment by chevoldavis** [comment]
Thanks Brock!!! I indeed did have 2 versions running (one from my html template and another loaded from npm). I removed the one from my html template and vue-full-calendar now is working fine. I have some issues with my html template now, but I can work thru those. Thanks again Brock, this solved my issue and my events are now refetching when I add new events!

**Comment by BrockReece** [comment]
Ah perfect, glad that worked.

Cheers
Brock
