### ISSUE TITLE
how to add locale file in this vue2 component

### ISSUE THREAD

**Issue by alucardxpmusic** [CroudSupport/vue-fullcalendar#50]
There's a better way  import (fullcalendar/dist/locale/zh-cn.js) file after used vue component( Vue.use(require('vue-full-calendar')) ) ?  I don't want to add files(fullcalendar.css, fullcalendar.js, zh-cn.js)) in index.html page.

**Comment by BrockReece** [comment]
You should be able to import them with something like this...

```
#Main.js
import 'fullcalendar/dist/locale/zh-cn.js'
```

```
#App.vue
<style>
  @import '~fullcalendar/dist/fullcalendar.css';
</style>
```

No need to include fullcalendar.js, this is already imported with this plugin.

**Comment by alucardxpmusic** [comment]
i import 'fullcalendar/dist/locale/zh-cn.js' in main.js file,
the method is really effective, thank you very much..

**Comment by BrockReece** [comment]
No problem, glad to help.
