### ISSUE TITLE
Example project stop working after updating packages deps

### ISSUE THREAD

**Issue by razerraz** [CroudSupport/vue-fullcalendar#51]
Steps to reproduce ::
clone example project, populate modules, everything works
update dependency tree with ncu -u, install upgrades, then Vue complains about "template or render function not defined"

upgrade tree ::
autoprefixer                         ^6.7.2  →   ^7.1.4 
 babel-loader                        ^6.2.10  →   ^7.1.2 
 chalk                                ^1.1.3  →   ^2.1.0 
 css-loader                          ^0.26.1  →  ^0.28.7 
 eslint                              ^3.14.1  →   ^4.6.1 
 eslint-config-airbnb-base           ^11.0.1  →  ^12.0.0 
 eslint-friendly-formatter            ^2.0.7  →   ^3.0.0 
 eslint-plugin-html                   ^2.0.0  →   ^3.2.1 
 extract-text-webpack-plugin          ^2.0.0  →   ^3.0.0 
 file-loader                         ^0.10.0  →  ^0.11.2 
 opn                                  ^4.0.2  →   ^5.1.0 
 optimize-css-assets-webpack-plugin   ^1.3.0  →   ^3.1.1 
 vue-loader                          ^11.1.4  →  ^13.0.4 
 vue-style-loader                     ^2.0.0  →   ^3.0.1 
 webpack                              ^2.2.1  →   ^3.5.6 
 webpack-merge                        ^2.6.1  →   ^4.1.0

Edit : after some trys, found that downgrading vue-loader solve the issue

**Comment by BrockReece** [comment]
I think the issue is with how vue-loader 13 deals with `require` statements I made a quick change yesterday but haven't published this to NPM yet.

You can try installing this latest version and let me know if this has fixed it.
```
npm install https://github.com/CroudSupport/vue-fullcalendar.git
- or -
yarn add https://github.com/CroudSupport/vue-fullcalendar.git
```

**Comment by razerraz** [comment]
got fatal: TypeError: "exports" is read-only 
when adding Vue.use(require('vue-full-calendar'))

**Comment by BrockReece** [comment]
Try again now. I think I broke the export of my plugin with my latest changes. That last commit should have fixed it though.

**Comment by BrockReece** [comment]
I have just upgraded to the latest verion of vue-loader on my example repo and it all appears to be working. https://github.com/BrockReece/vue-fullcalendar-example/commit/3955c75984cad8cbf45e10031aa0d7ad09fcd988

**Comment by razerraz** [comment]
It doesn't work for my project ::
got full-calendar component not found with Vue.use(require('vue-full-calendar')) in main.js
got template or render function not defined after adding import FullCalendar from 'vue-full-calendar' and FullCalendar to component prop in the component vue file

besides, npm version work like a charm with vue-loader 11 on this project...

Maybe I'm missing something..

will try from your example soon

**Comment by BrockReece** [comment]
Ah yeah sorry, you will need to change your a require to an import
statement. If you look at my recent commits on the example repo it should
help you out. Sorry I am away from my laptop at the moment.

**Comment by ergonomicus** [comment]
Don't know if it is the same issue, but for me fullcalendar is blank after upgrading to 2.1

**Comment by ergonomicus** [comment]
@BrockReece I think you should reopen this issue...

**Comment by BrockReece** [comment]
Ok, thanks.

Can you tell me if there are any errors in the console and can you also tell me which version of vue-loader you are using?

**Comment by BrockReece** [comment]
I have just tested in my example app with vue-loader 12.x and 13.x and it appears to be working.
Can you confirm that you are loading the plugin via an `import` statement as opposed to a `require`?
```js
import FullCalendar from 'vue-full-calendar'
Vue.use(FullCalendar)
```

**Comment by razerraz** [comment]
works like a charm for me, and I prefer doing import, more explicit.
congrats and thanks !

**Comment by ergonomicus** [comment]
So sorry, I have removed dependency from package.json and reinstalled version 2.1.0 and everything is back to normal now.

I guess that compiler messed up something, since I don't have any issues now.

I have used
```
import FullCalendar from 'vue-full-calendar'
Vue.use(FullCalendar)
```
as stated above.

Once again, I am sorry, I should have tried reinstalling before raising this issue.

**Comment by BrockReece** [comment]
No problem, glad it is sorted.
Thanks for you help guys :)
