### ISSUE TITLE
Please require jquery in your component

### ISSUE THREAD

**Issue by getriebesand** [CroudSupport/vue-fullcalendar#52]
Please put 

var $ = require('jquery')

in your FullCalendar.vue.

I don't need jquery but have another lib which defines $

And I think if your component depends on jquery, it should require it by it self.

**Comment by BrockReece** [comment]
I'm not sure if the $ definition is enough for fullcalendar to work as it is a jQuery plugin. See this [codepen](https://codepen.io/BrockReece/pen/EwNrRM), the console ouput gives the following

```
Uncaught ReferenceError: jQuery is not defined
```

What do you have that defines $?

**Comment by getriebesand** [comment]
fullcalender imports jquery too. So we don't have to care about that.

**Comment by BrockReece** [comment]
But window.jQuery needs to be defined for jQuery to load plugins I think.
So even if I am importing jQuery into the component. 
```
import $ from 'jQuery'
```
We are still going to see 
```
Uncaught ReferenceError: jQuery is not defined
```

Maybe I'm wrong?

**Comment by BrockReece** [comment]
Oh sorry, I see what you mean.

Ok, I'll commit something into a new branch and if you could test with your setup I will merge it in when we are ready.

**Comment by getriebesand** [comment]
Thank you. 
Now it works with my setup.

**Comment by BrockReece** [comment]
Perfect, I will merge it in.
Thanks for your contribution
