### ISSUE TITLE
import to my vue component not rendering

### ISSUE THREAD

**Issue by maverickchangithub** [CroudSupport/vue-fullcalendar#57]
when i am trying to import this component to my project --a laravel-backend -- , to a single file component , it does not render.

i know , it is 100% my problem , and i really need some advice. thanks !

btw , i download the sample you gave , it works , but i just cannot use it  in my project.

**Comment by BrockReece** [comment]
Can you share some code?
Possibly your main.js and also your .vue file where you are trying to render the calendar?

**Comment by maverickchangithub** [comment]
@BrockReece 
 i am using a single file vue component.

`
<template>
     <div id="calendar"></div>  
</template>

<script>
        require('fullcalendar'); //this line is before i use vue-calendar , i was using jquery , i did install fullcalendar(the js) from npm.

	 import FullCalendar from 'vue-full-calendar';

	import element from 'element-ui';

	import moment from 'moment';

	 Vue.use(FullCalendar);

        export default {

          //  vue codes

       }
`

**Comment by BrockReece** [comment]
It looks like you are loading the plugin correctly, but aren't actually using the component in the template markup.
```html
<template>
  <full-calendar :events="events"></full-calendar>
</template>
```

FYI the `vue-full-calendar` lib already includes the fullcalendar lib so you won't need that first require statement.

Hope that helps? If this still doesn't work, can you show me your package.json and include any errors that you are seeing in the console.

**Comment by maverickchangithub** [comment]
it is working now after i rewrite the whole component .....

thanks !!!

**Comment by BrockReece** [comment]
No problem.

**Comment by maverickchangithub** [comment]
now i got another problem 
the title render undefined , some one says it's moment.js problem . i checked the fullcalendar package.json , it says dependency of moment version is ^2.9.0 , but moment.js is currently 2.18.1 , really confused....

**Comment by BrockReece** [comment]
Can you share any screenshots or console logs?

**Comment by maverickchangithub** [comment]
i use fullcalendar 3.4.0 , then the undefined disappears.

but , there is a very strange thing , daySelect not working right , i googled , it might be a jquery-ui issue.

The issue is some of the date could not be selected , for example : edge could select first 35 dates , last 7 dates could not ; Chrome is same when there is no events , when 1 event created , only could select first 14 dates .  I check the console , when click , some date was given a class 'unselectable' dynamically .

if using pure jQuery fullcalendar , this would not happen .

and one more thing , refreshEvents and rerenderEvents sometimes(worked fine first 1 or 2 rounds) not working  both in edge and Chrome.

Thanks for your patience , you did a great job!

**Comment by BrockReece** [comment]
This may be down to your projects dependencies and webpack loading different instances of the same lib. For example, my lib depends on fullcalendar 3.4.x, so it makes sense that syncing up these versions has fixed something. If you are using yarn you can run a command to see how many different versions of the same dependancy your app is using. (I am sure there will be a similar command if you are using npm)

```bash
yarn list fullcalendar
yarn list jquery
```

Just as an FYI though, all this lib does is wrap fullcalendar in the same way that you would have done with jQuery, it isn't really doing anything clever under the hood.

**Comment by maverickchangithub** [comment]
yes , you are right . Now i upgrade fullcalendar to 3.5 , everything is fine.

But i really don't know how to fix jquery-ui issue , and npm list jquery-ui does not exist. it seems that fullcalendar include jquery-ui in its own js file.....

totally have no idea to do ....

thanks a lot!

**Comment by BrockReece** [comment]
Is your code on Github anywhere? I will be happy to have a look for you?

**Comment by maverickchangithub** [comment]
i solved this problem by use a style `overflow:auto;` on the wrapper of the component.
this is a simple css problem , just like the original one i had 

thanks ! this issue could be closed . it is really my fault.

**Comment by BrockReece** [comment]
Great.
