### ISSUE TITLE
how to enable eventResize ?

### ISSUE THREAD

**Issue by maverickchangithub** [CroudSupport/vue-fullcalendar#58]
hi Brock , me again....
sorry for this little stupid question : 

i just cannot enable event resize (month view , week and day seems ok) , is there any condition i should write in the parent component?

in my parent component:
```
<full-calendar ref="calendar" :events="events" @event-selected="eventSelected" @day-click="dayClick" @event-resize="eventResize" @event-drop="eventDrop"></full-calendar>
```

and btw , if you can give me some advice to enable drop event from outside in vue way.

thanks a lot !!

**Comment by BrockReece** [comment]
Hi @maverickchangithub 
So this component should be editable by default. So if you resize an event (drag the bottom of an event) it should emit  the `event-resize` event. It looks like you are listening to the `event-resize` event and it should be firing a method called `eventResize` in your parent component. Is it not firing this method?

Anything in the console to help us out here?

**Comment by maverickchangithub** [comment]
hi Brock , i tested , in week and day view , it fired the method ,works fine and could be resized .

But , in month view , when mouse hover on a event , the cursor does not change like it did in jquery mode. I think event resize in month view would be dragging left and right side of the event , which i could not do now.

And for the 2nd question , how to use drag and drop a event from outside to the calendar?

Thanks !

**Comment by BrockReece** [comment]
I'm not sure why the month view would make a difference. Could you share some code of your old jquery based project and I will look at migrating it for you.

As I said in an earlier message, all this package does is wrap fullcalendar into a Vue component, so anything you are able to do in your jQuery version should work in this component.

**Comment by maverickchangithub** [comment]
you are 100% right . i found it should assign allDay to an event .....

Sorry ! My fault again.....

**Comment by BrockReece** [comment]
That looks quite nifty, I am guessing they are using [this](https://fullcalendar.io/docs/dropping/drop/) in their config.

Looks like you will need to build a [jQuery ui draggable](https://jqueryui.com/draggable/) list of possible events too.

**Comment by maverickchangithub** [comment]
thanks Brock! By learning your code , now i start to understand something.

**Comment by BrockReece** [comment]
Hi @maverickchangithub 

I am happy to help out but I am going to close this now though as there isn't actually an issue with this project.
