### ISSUE TITLE
an error on my project

### ISSUE THREAD

**Issue by HiHeidiYoung** [CroudSupport/vue-fullcalendar#6]
![default](https://cloud.githubusercontent.com/assets/11813058/21537995/1b87d38c-cdd3-11e6-9d5e-ba89e38adee5.png)

**Comment by BrockReece** [comment]
Hi @HiHeidiYoung ,

Can you tell me which version of Vue and vue-full-callendar you are using?

Cheers
Brock

**Comment by HiHeidiYoung** [comment]
@BrockReece   1.0.0

**Comment by BrockReece** [comment]
And which version of Vue are you using?
vue-full-callendar 1.0.0 is designed to work with Vue 2.x

**Comment by kszyrvercobrador** [comment]
You need to pull in FullCalendar library from here https://fullcalendar.io/download/ and add to your project.

**Comment by BrockReece** [comment]
@HiHeidiYoung 
I am guessing this has now been solved?
