### ISSUE TITLE
Vuex + eventSources

### ISSUE THREAD

**Issue by lucassmacedo** [CroudSupport/vue-fullcalendar#60]
Hello guys, i want add Vuex + eventSources in my app.. its possible?
I try but i have no success.. thanks!

**Comment by BrockReece** [comment]
Hello @lucassmacedo,

There is a section on the readme with [eventSources examples](https://github.com/CroudSupport/vue-fullcalendar#using-a-json-feed).

And this plugin will work whether you use Vuex in your application or not.

I hope that helps?

**Comment by lucassmacedo** [comment]
Thanks
