### ISSUE TITLE
Error on the package

### ISSUE THREAD

**Issue by raphcadiz** [CroudSupport/vue-fullcalendar#61]
VM2482:1 Uncaught SyntaxError: Unexpected token import
`
import FullCalendar from './components/FullCalendar.vue';`

**Comment by BrockReece** [comment]
Can you tell me a bit more about your project, this will be hard to replicate and debug without any context.

Are you using webpack/browserify/rollup?
What version of vue-full-calendar are you using?
What version of vue-loader are you using?

**Comment by raphcadiz** [comment]
I'm using Webpack. Here is the versions of packages you asked

```
"vue-full-calendar": "^2.0.2"
"vue-loader": "^11.0.0",
```

**Comment by BrockReece** [comment]
Are these the actual versions, or just what is in your package.json

```bash
npm list vue-full-calendar
npm list vue-loader
```

As these are older versions, I guess this has been working for you up until some point?

**Comment by raphcadiz** [comment]
So this are the actual versions
```
vue-loader@11.3.4 
vue-full-calendar@2.1.2 
```

**Comment by BrockReece** [comment]
Ok great, what does your main.js look like?

**Comment by raphcadiz** [comment]
```
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import VueRouter from 'vue-router'
import VueResource from 'vue-resource'
import VueCookies from 'vue-cookies'
import VeeValidate from 'vee-validate'
import VueCalendar from 'vue-full-calendar'
import routes from './routes.js'
import * as VueGoogleMaps from 'vue2-google-maps'

require('sweetalert2/dist/sweetalert2.min.css')

const config = {
  errorBagName: 'errors', // change if property conflicts.
  fieldsBagName: 'fields',
  delay: 0,
  locale: 'en',
  dictionary: null,
  strict: true
}

// We want to apply VueResource and VueRouter
// to our Vue instance
Vue.use(VueResource)
Vue.use(VueRouter)
Vue.use(VueCookies)
Vue.use(VeeValidate, config)
Vue.use(VueCalendar)

// Global components
import AppHeader from './components/Header.vue'
import Sidebar from './components/Sidebar.vue'
import Aside from './components/Aside.vue'
import Footer from './components/Footer.vue'

const router = new VueRouter({
  routes, // short for routes: routes
  linkActiveClass: 'active',
  history: true
})

new Vue({
  components: {
    'app-header': AppHeader,
    'app-sidebar': Sidebar,
    'app-aside': Aside,
    'app-footer': Footer
  },
  router,
  methods: {
    isAdminPage: function (path, name) {
      let publicComponents = ['/login', '/register', '/signup', '/welcome']
      return publicComponents.indexOf(path) >= 0 || publicComponents.indexOf(name) >= 0
    }
  }
}).$mount('#app')

```

**Comment by BrockReece** [comment]
Sorry, I am really struggling to replicate this issue.
Was it ever working at any time and is there anything you have changed/installed since then?

Cheers
Brock

**Comment by renztoygwapo** [comment]
Do you have some feedback for this issue ? We faced the same error after we run "npm update" then this modules not working anymore. please let us know.

Cheers,
Florence

**Comment by BrockReece** [comment]
As I said before, I am struggling to replicate the issue with the exact versions that you are using, I have even tried adding all of your other dependencies but still unable to break things.

Is this code somewhere public so I can download and try to fix in place?

**Comment by BrockReece** [comment]
Hi @renztoygwapo 

Sorry for my short answer this morning. Can you let me know which version you were using before your latest npm update? I am happy to help, just struggling to replicate the issue at the moment.

**Comment by BrockReece** [comment]
BTW, have you guys taken note of this release note?
https://github.com/CroudSupport/vue-fullcalendar/releases/tag/v2.1.0

**Comment by renztoygwapo** [comment]
Hello, Thanks for your response, my current version for the npm and noded is this one.
![image](https://user-images.githubusercontent.com/4898681/31690117-4dffb762-b3c4-11e7-9e86-f62a4103a228.png)
then, I used the import like your release note, and the vue-full-calendar I used is this one 
vue-full-calendar@2.1.2 which is your latest release. 

After I run npm update, I decided to use your previous version which vue-full-calendar@2.0.2
then it will fix the error. 
Now I guess it's the error in the package on your latest release I guess, 
Hope you can replicate the issue. 
Thanks and More Power!

All the Best,
Florence

**Comment by BrockReece** [comment]
Hi @renztoygwapo 

Thanks for the detail in your last message. 
Can you do me a favour and install version 2.0.6? This is the latest version before the risky changes I had to make for the latest version of vue-loader.

Cheers
Brock

**Comment by renztoygwapo** [comment]
Hi @BrockReece 
Yup, it still working on the version 2.0.6. 

hopefully you can fixed this in your latest release which is the version 2.1.2

Thanks

**Comment by BrockReece** [comment]
Ok, are you using babel? if so what does your .babelrc and your webpack config look like?

**Comment by renztoygwapo** [comment]
Yup, Here's the babelIrc config
![image](https://user-images.githubusercontent.com/4898681/31711351-67a66092-b42a-11e7-9d24-504e7147086d.png)
also, I am using the vue webpackage templates actually.

**Comment by BrockReece** [comment]
So while I am trying to replicate and fix this issue, @raphcadiz I think forcing the version to be 2.0.6 will work for you.

**Comment by BrockReece** [comment]
@renztoygwapo I have the same babel config, any chance I could see your babel loader config in webpack?
Sorry about this, I do appreciate your patience and help with this.

**Comment by BrockReece** [comment]
Hi guys,

Told you I wasn't going to give up on this.
I have just released a new version 2.1.3 which I think will fix this for you 👍 

Let me know.

**Comment by renztoygwapo** [comment]
cool, thanks :) will give it a try

**Comment by houseoftech** [comment]
@BrockReece I've been getting some errors since 2.1.4 with the .babelrc file addition. Everything works find with `npm run dev`, but when I try a production build, `npm run production` I get the following error:

````
Module build failed: ReferenceError: Unknown plugin "transform-runtime"
````

It seems I don't have this plugin installed. Should the vue-full-calendar package.json specify this as a dependency?

I'm a bit new to npm and I don't really understand everything about the plugin. But it does mention here https://www.npmjs.com/package/babel-plugin-transform-runtime that the transform-runtime should only be run in development.

I'm using Laravel mix 1.6.1

**Comment by BrockReece** [comment]
Cool I have added this dependency in #83 if you want to help me test?

**Comment by houseoftech** [comment]
@BrockReece #83 fixes the issue for me, thanks.

**Comment by BrockReece** [comment]
Good to hear, thanks for the feedback :)
