### ISSUE TITLE
ajax request on full calendar

### ISSUE THREAD

**Issue by zoat** [CroudSupport/vue-fullcalendar#62]
Hello ,
I try to make ajax request with vu full calendar  but it did nt work

<template>
  <div id="main">
    <full-calendar :event-sources="eventSources"></full-calendar>
  </div>
</template>

<script>
export default {
    name: 'home',
    computed: {
      eventSources(start, end, timezone,callback) {
        const self = this;
        return $.ajax({
          url: '/toto'
          type: "GET",
          dataType: "json",
          success: function (data) {
            callback(data);
                  },
          error: function () {
                    }
        });
      },
    },

  }
</script>

<style>

**Comment by BrockReece** [comment]
Hi @zoat 
Is it throwing any errors?
Is it making the request but not dealing with the response?

**Comment by zoat** [comment]
<template>
 <button v-on:click="getEvents" class="btn btn-primary btn-md">
      Get Events
    </button>
<full-calendar :event-sources="eventSources"></full-calendar>
</template>

<script>
data() {
      return {
        errormsg: '',
        showModal: true,
        eventSources: [],
       
    },
}
  methods: {
getEvents: function () {
        const that = this;
        $.ajax({
          url: "/url",
          type: "GET",
          dataType: "json",
          success: function (data) {
            console.info("Events,", data);
//the form of my data is  like this
 //"id": "500653153",
  //                    "title": "test",
   //                   "start": "2017-10-09T00:00:00",
   //                   "end": "2017-10-09T00:00:00",
    //                  "url": "",
    //                  "className": "",
     //                 "allDay": true,
      //                "editable": true,
    //                  "durationEditable": true,
   //                   "startEditable": true,
 //                     "backgroundColor": "#ffff",
  //                    "borderColor": "#ffff",
   //                   "textColor": "#ffff"
           that.eventSources = data;  
}
    </script>   

and my error is 

[Vue warn]: Error in event handler for "rebuild-sources": "TypeError: _this.eventSources.map is not a function"

found in

---> <FullCalendar> at node_modules\vue-full-calendar\components\FullCalendar.vue
       <Wrapper> at src\components\wrapper\Wrapper.vue
         <NavBar> at src\components\NavBar.vue
           <Main> at src\components\Home.vue
             <App> at src\App.vue
               <Root>
warn @ vue.esm.js?65d7:476
handleError @ vue.esm.js?65d7:559
Vue.$emit @ vue.esm.js?65d7:2333
handler @ FullCalendar.vue?2ca5:183
run @ vue.esm.js?65d7:3008
flushSchedulerQueue @ vue.esm.js?65d7:2760
(anonymous) @ vue.esm.js?65d7:698
nextTickHandler @ vue.esm.js?65d7:645
Promise resolved (async)
timerFunc @ vue.esm.js?65d7:660
queueNextTick @ vue.esm.js?65d7:708
queueWatcher @ vue.esm.js?65d7:2847
update @ vue.esm.js?65d7:2984
notify @ vue.esm.js?65d7:775
reactiveSetter @ vue.esm.js?65d7:997
proxySetter @ vue.esm.js?65d7:3109
success @ Wrapper.vue?e5b3:144
fire @ jquery.js?27d9:3317
fireWith @ jquery.js?27d9:3447
done @ jquery.js?27d9:9272
(anonymous) @ jquery.js?27d9:9514
XMLHttpRequest.send (async)
send @ jquery.js?27d9:9566
ajax @ jquery.js?27d9:9173
getEvents @ Wrapper.vue?e5b3:137
boundFn @ vue.esm.js?65d7:179
invoker @ vue.esm.js?65d7:1821
vue.esm.js?65d7:563 TypeError: _this.eventSources.map is not a function
    at VueComponent.eval (FullCalendar.vue?2ca5:158)
    at VueComponent.Vue.$emit (vue.esm.js?65d7:2331)
    at VueComponent.handler (FullCalendar.vue?2ca5:183)
    at Watcher.run (vue.esm.js?65d7:3008)
    at flushSchedulerQueue (vue.esm.js?65d7:2760)
    at Array.eval (vue.esm.js?65d7:698)
    at nextTickHandler (vue.esm.js?65d7:645)
    at <anonymous>
handleError @ vue.esm.js?65d7:563
Vue.$emit @ vue.esm.js?65d7:2333
handler @ FullCalendar.vue?2ca5:183
run @ vue.esm.js?65d7:3008
flushSchedulerQueue @ vue.esm.js?65d7:2760
(anonymous) @ vue.esm.js?65d7:698
nextTickHandler @ vue.esm.js?65d7:645
Promise resolved (async)
timerFunc @ vue.esm.js?65d7:660
queueNextTick @ vue.esm.js?65d7:708
queueWatcher @ vue.esm.js?65d7:2847
update @ vue.esm.js?65d7:2984
notify @ vue.esm.js?65d7:775
reactiveSetter @ vue.esm.js?65d7:997
proxySetter @ vue.esm.js?65d7:3109
success @ Wrapper.vue?e5b3:144
fire @ jquery.js?27d9:3317
fireWith @ jquery.js?27d9:3447
done @ jquery.js?27d9:9272
(anonymous) @ jquery.js?27d9:9514
XMLHttpRequest.send (async)
send @ jquery.js?27d9:9566
ajax @ jquery.js?27d9:9173
getEvents @ Wrapper.vue?e5b3:137
boundFn @ vue.esm.js?65d7:179
invoker @ vue.esm.js?65d7:1821

**Comment by BrockReece** [comment]
Ah ok, so I think you have confused [event sources](https://fullcalendar.io/docs/event_data/Event_Source_Object) and [events](https://fullcalendar.io/docs/event_data/events_array/). Your eventSources should be an array of objects which will look similar to this...
```js
[
  {
    events(start, end, timezone, callback) {
      $.ajax({
        url: "/url",
        type: "GET",
        dataType: "json",
        success(data) {
          callback(data)
        },
      })
    },
  },
]
```
The `events` method is fired when the calendar loads and every time there is a change to the calendar that warrants a reload of data. The `callback` variable that is passed in to `events` is a function which expects an array of event objects.

I hope this helps?
Cheers
Brock

**Comment by zoat** [comment]
thanks It  work  



    <full-calendar :event-sources="eventSources" ref="calendar"></full-calendar>





  var events_url = '';
  export default {
    name: 'Wrapper',
    data () {
      return {
        events: {}
      }
    },

    methods: {
      getEvents () {
        const that = this;
        $.ajax({
          url: url,
          type: "GET",
          dataType: "json",
          success (data) {
        
            that.events = data;
          },
          error: function () {
      
          }
        });
      }
    },
    computed: {
      eventSources () {
        return [{
          events: this.events
        }]
      }
    }
  }
</script>
