### ISSUE TITLE
toggle week  in  vu full calendar

### ISSUE THREAD

**Issue by zoat** [CroudSupport/vue-fullcalendar#63]
Hello 
I  looking for a way to display or not the week in the calendar view

In my template  I have
'''full-calendar :event-sources="eventSources" ref="calendar" id="calendar"full-calendar''''

 this.$refs.fullCalendar('option',{weekends: false});

**Comment by BrockReece** [comment]
I think you almost had it, but you need to use fireMethod on the fullCalendar component. 

Also, you need to make sure your `$refs` match the `ref` in the template 

```js
this.$refs.calendar.fireMethod('option', { weekends: false })
```

**Comment by zoat** [comment]
thank Brock it work.
`<full-calendar :event-sources="eventSources" ref="calendar"  id ="calendar"></full-calendar>`


 toggleWeekEnd: function () {
       /* $('#calendar').fullCalendar('option', {
          weekends: this.weekEnd
        });*/also work
        this.$refs.calendar.fireMethod('option', { weekends: this.weekEnd });
       }
