### ISSUE TITLE
drag external event  in vu full calendar

### ISSUE THREAD

**Issue by zoat** [CroudSupport/vue-fullcalendar#67]
hello @BrockReece

I am searching  a way to drag  and drop external event in  full callendar vue  like 
 done in https://codepen.io/subodhghulaxe/pen/qEXLLr.

Have you a exemple which can help me 

Tanks you

**Comment by BrockReece** [comment]
I haven't got an example like this, but it is probably something I could help you with.
How far have you got with it?

**Comment by zoat** [comment]
my first task is to make  my external event  droppable  for this I use  from 'vuedraggable'

in my template i have 
` 
<draggable v-model="daggableAffairesList">
                  <div class="tache bg-planning" v-for="affaire in daggableAffairesList">{{affaire.label}}<a class="float-right"><i class="fa fa-star text-white" aria-hidden="true"></i></a>
                  </div>
                </draggable>`

`<script>
import draggable from 'vuedraggable'
export default {
    name: 'CompA',
    components: { draggable},

mounted () {
// this alllows  things to be  dropped onto the calendar
      $('#calendar').fullCalendar({droppable: true});
      this.searchBussinessAction(),
     

}
    }
</script>`
and the next step is to drop it  on my vu full calendar

**Comment by BrockReece** [comment]
Is vue-draggable a jQuery ui draggable wrapper?

I think [fullcalendar](https://fullcalendar.io/docs/dropping/droppable/) is only compatible with jQuery ui draggable.

**Comment by zoat** [comment]
https://github.com/SortableJS/Vue.Draggable

**Comment by BrockReece** [comment]
Did you want me to look for you?

That link said that it has no dependency on jQuery, so I guess not.

**Comment by zoat** [comment]
thanks Brock  I will be  a great help  for me  I am trying to  drag  external event  in full calendar  but still  don't know  the best  way  to do it.

**Comment by BrockReece** [comment]
Here is an example of using vue-full-calendar instead of the standard jQuery plugin

https://codepen.io/BrockReece/pen/LOPwyK?editors=0010

Ignore lines 47 - 208 in the js. This is me simulating loading vue-full-calendar.

**Comment by zoat** [comment]
thank Brock very much I am tryng to adapt it to my vu- cli  project.

**Comment by zoat** [comment]
Please @BrockReece Brock it is possible to have this exemple in   https://github.com/BrockReece/vue-fullcalendar-example, been  a begginer in vu , I have some problem to integrate it in vu cli project.
Thank

**Comment by BrockReece** [comment]
Ok, with the greatest of respect, I feel as through I may now be doing your job for you. If you can tell me the specific issues you are having or concepts that you aren't understanding, I am happy to address these and hopefully teach you how to fish as opposed to catching the fish for you.

The problem with putting up an official example is that it will become something else I will need to find time to support. If you are happy to share (and support) an example with the community, we would all be very grateful, and that is something I am willing to help you with.

**Comment by zoat** [comment]
I finally find the solution  I change  $(document).ready(function()  by mounted
And It work Thank   for  your help

**Comment by BrockReece** [comment]
Glad to hear it, if you want to contribute this to the example repo, let me know.
