### ISSUE TITLE
Scheduler resources issue

### ISSUE THREAD

**Issue by thomhess** [CroudSupport/vue-fullcalendar#69]
Hello, I've added fullcalendar-scheduler to my project, and it works mostly fine. Still, there are some stuff missing in todays FullCalendar.vue file, i.e. support for resources. Is there any extra content available for the scheduler additions, or will I have to write it all myself? My problem atm is setting up a render for resources.

**Comment by BrockReece** [comment]
Hi @thomhess 

You can use the `config` prop to pass in anything that the component doesn't explicitly deal with. Looking at the [scheduler's docs](https://fullcalendar.io/docs/scheduler/) something like this should work...

```js
config: {
    defaultView: 'timelineMonth',
    events: [
        // events go here
    ],
    resources: [
        // resources go here
    ]
    // other options go here...
},
```

**Comment by thomhess** [comment]
Ahh, I didn't realize that. Thanks! Is it possible to have the config as a computed property?

**Comment by BrockReece** [comment]
Technically it is, but I don't think it will react to changes.
