### ISSUE TITLE
Reactive events

### ISSUE THREAD

**Issue by greggnic** [CroudSupport/vue-fullcalendar#7]
Are the events supposed to be reactive? I am able to render the initial events:

`full-calendar(ref='full-calendar',:events="filteredEvents")`

However, any update to the events are not shown on the calendar. I also tried to trigger the 'rerender-events' event on the full-calendar but did not see the updated events rendered:

`window.jQuery(this.$refs['full-calendar']).trigger('rerender-events')`

Has anyone been able to update events and see the changes on the calendar? FYI, my filteredEvents are computed properties and I am able to see the updates with `pre {{filteredEvents}}`. I've also tried to render the vuex store object itself and make changes to that object to no avail.

**Comment by greggnic** [comment]
Got it working by updating the watch code to 
```
  watch: {
    events: {
      deep: true,
      handler (val) {
        const cal = $(this.$el)
        cal.fullCalendar('removeEvents')
        cal.fullCalendar('addEventSource', this.events)
        cal.fullCalendar('rerenderEvents')
      }
    }
  },
```

Probably not the most efficient way to do things though :/

**Comment by ankurk91** [comment]
@greggnic 
You patch worked for me.
