### ISSUE TITLE
Dragging events in last row and prev/next days of month

### ISSUE THREAD

**Issue by damirsel** [CroudSupport/vue-fullcalendar#70]
Issue occurs on version 0.0.4 with vuejs version 1.0.28. when dragging events from/to days on last bottom row. 

Console shows: 

> Uncaught TypeError: Cannot read property 'component' of undefined: fullcalendar.min.js:7

Error also occurs when dragging days on/from starting days of a next month and last days of previous month if that option is enabled.

**Comment by BrockReece** [comment]
That looks like an error coming from fullcalendar as opposed to this wrapper?

**Comment by damirsel** [comment]
yes, once updated from 3.6.1 to 3.6.2 appears to be working properly.

Thanks.

**Comment by BrockReece** [comment]
Good to hear :)
