### ISSUE TITLE
Drag Drop External Events

### ISSUE THREAD

**Issue by satinderrana** [CroudSupport/vue-fullcalendar#72]
Hi

Thank you for this amazing vue integration with full calendar. But i am having issue while trying to make the calendar droppable. I am using the latest version of vue-fullcalendar. Here is my markup

`<full-calendar :events="calendar.events" :header=calendar.header :sync="calendar.sync"
                        :allDaySlot="calendar.allDaySlot" :config="calendar.config" :editable="calendar.editable">
                    </full-calendar>`

and in my vue data i have:

`calendar: {
                    events: [],
                    header: {
                        left:   'prev,next today',
                        center: 'title',
                        right:  'agendaWeek,month'
                    },
                    config: {
                        allDaySlot: true,
                        columnFormat: "D ddd",
                        droppable: true,
                        selectable: false,
                        timeFormat: 'H(:mm)'
                    },
                    editable: true,
                    defaultView: 'agendaWeek',
                    sync: true
                }`

I have tried my best to debug but i am not able to find a solution for this. please help

**Comment by BrockReece** [comment]
Hi @satinderrana,

I think you need to add a drop method to your config to deal with the dropped items.

Here is one that I made earlier
https://codepen.io/BrockReece/pen/LOPwyK?editors=0010

**Comment by satinderrana** [comment]
Hi

thanks for such a quick reply. I appreciate it. I will try and do it the way you have suggested though I would like to tell you the issue here so maybe you can help me eliminate the root cause.

I am using your package in laravel environment. Now, laravel's default js file (app.js) includes the jquery and assign it to window object as well something like window.$ = window.jQuery = require('jquery')]
app.js also has vue

To use your package i have created another js file with the content as follows:

`import FullCalendar from 'vue-full-calendar'
Vue.use(FullCalendar)`

in my view file i include "app.js" and "calendar.js" (the js which resulted from the above and then write the following code:

`var app = new Vue({
            el: '#main_content',
            data: {
                images: JSON.parse('{!! addslashes($data['user']->images->toJson()) !!}'),
                calendar: {
                    events: [],
                    header: {
                        left:   'prev,next today',
                        center: 'title',
                        right:  'agendaWeek,month'
                    },
                    config: {
                        allDaySlot: true,
                        columnFormat: "D ddd",
                        droppable: true,
                        selectable: false,
                        timeFormat: 'H(:mm)'
                    },
                    editable: true,
                    defaultView: 'agendaWeek',
                    sync: true
                }
            },
            directives: {
                fcevent: {
                    bind: function(el) {
                        // Different colors for events
                        $(el).css({'backgroundColor': $(el).data('color'), 'borderColor': $(el).data('color')});

                        // Store data so the calendar knows to render an event upon drop
                        $(el).data('event', {
                            title: $.trim($(el).html()), // use the element's text as the event title
                            color: $(el).data('color'),
                            stick: true // maintain when user navigates (see docs on the renderEvent method)
                        });

                        // Make the event draggable using jQuery UI
                        $(el).draggable({
                            start: function(event, ui) {
                                jQuery.event.dispatch.apply($(document)[0], [event]);
                            },
                            zIndex: 999,
                            revert: true, // will cause the event to go back to its
                            revertDuration: 0 // original position after the drag
                        });
                    }
                }
            },
            mounted: function(){
                Dropzone.autoDiscover = false;

                $(function() {
                    $("#dropzone_multiple").dropzone({
                        paramName: "upload_image", // The name that will be used to transfer the file
                        dictDefaultMessage: 'Drop files to upload <span>or CLICK</span>',
                        init: function() {
                            this.on("success", function(file, response) { app.images.push(response); });
                        }
                    });
                });
            },
            methods: {
                drop: function(event) {
                    console.log("dropped");
                }
            }
        });`

and in the html i have

`<full-calendar :events="calendar.events" :header=calendar.header :sync="calendar.sync"
                        :allDaySlot="calendar.allDaySlot" :config="calendar.config" :editable="calendar.editable">
                    </full-calendar>`

and for the draggable events

`<div class="fc-event" data-color="#546E7A" v-for="(image, index) in images" v-fcevent>Sauna and stuff</div>`

when i drag any object, except the draggable event, the dispatch: method of the jquery of "calendar.js" is called. however, when i drag the external event i.e. the div with directive v-fcevent, the dispatch of jQuery of "app.js" is called and i think that i messing up the drag and drop

can you please suggest what i am doing wrong here?

**Comment by BrockReece** [comment]
Sorry, I have read through your code above but I can't see anything obvious.

I'm not sure that I understand this statement.

> when i drag any object, except the draggable event, the dispatch: method of the jquery of "calendar.js" is called. however, when i drag the external event i.e. the div with directive v-fcevent, the dispatch of jQuery of "app.js" is called and i think that i messing up the drag and drop

If you add a drop function to your fullcallendar config, does that fire when you drop something on it?

**Comment by satinderrana** [comment]
Unfotunately it doesnt. But i guess its not the issue of your component so i will go ahead and delete this issue :)

**Comment by BrockReece** [comment]
If you figure it out, can you leave the solution here, it may help someone out.

**Comment by satinderrana** [comment]
Definitely I will. I will leave a detailed cause and solution when i figure this out

**Comment by satinderrana** [comment]
hi @lbdlbdlbdl Yes i was able to resolve the issue. It was caused because I included jquery on my page and there was another instance of jquery imported and used by vue-calendar. Are you doing the same thing?

**Comment by lbdlbdlbdl** [comment]
@satinderrana I'm just trying to enable drag'n'drop. 
I just  try to run this example in my NUXT project:
https://codepen.io/BrockReece/pen/LOPwyK?editors=0010

So, my code is below:
page/test/index.vue:

```
<template>
  <div id='wrap'>
    <div id='external-events'>
      <div id='external-events-listing'>
        <h4>Draggable Events</h4>
        <div class='fc-event' v-fcevent>My Event 1</div>
        <div class='fc-event' v-fcevent>My Event 2</div>
      </div>
      <p>
        <input type='checkbox' id='drop-remove' checked='checked' />
        <label for='drop-remove'>remove after drop</label>
      </p>
    </div>

    <full-calendar :config="config"></full-calendar>
    <div style='clear:both'></div>
  </div>
</template>

<script>
import moment from "moment";
import { FullCalendar } from "vue-full-calendar";

export default {
  components: {
    FullCalendar
  },
  directives: {
    fcevent: {
      bind: function(el) {
        $(el).data("event", {
          title: $.trim($(this).text()), // use the element's text as the event title
          stick: true // maintain when user navigates (see docs on the renderEvent method)
        });

        // Make the event draggable using jQuery UI
        $(el).draggable({
          start: function(event, ui) {
            jQuery.event.dispatch.apply($(document)[0], [event]);
          },
          zIndex: 999,
          revert: true, // will cause the event to go back to its
          revertDuration: 0 // original position after the drag
        });
      }
    }
  },
  data() {
    return {
      config: {
        header: {
          left: "prev,next today",
          center: "title",
          right: "month,agendaWeek,agendaDay"
        },
        editable: true,
        droppable: true, // this allows things to be dropped onto the calendar
        dragRevertDuration: 0,
        drop: function() {
          // is the "remove after drop" checkbox checked?
          if ($("#drop-remove").is(":checked")) {
            // if so, remove the element from the "Draggable Events" list
            $(this).remove();
          }
        },
        eventDragStop: function(event, jsEvent, ui, view) {
          if (isEventOverDiv(jsEvent.clientX, jsEvent.clientY)) {
            $("#calendar").fullCalendar("removeEvents", event._id);
            var el = $("<div class='fc-event'>")
              .appendTo("#external-events-listing")
              .text(event.title);
            el.draggable({
              zIndex: 999,
              revert: true,
              revertDuration: 0
            });
            el.data("event", { title: event.title, id: event.id, stick: true });
          }
        }
      }
    };
  }
};
</script>

<style>
body {
  margin-top: 40px;
  text-align: center;
  font-size: 14px;
  font-family: "Lucida Grande", Helvetica, Arial, Verdana, sans-serif;
}

#wrap {
  width: 1100px;
  margin: 0 auto;
}

#external-events {
  float: left;
  width: 150px;
  padding: 0 10px;
  border: 1px solid #ccc;
  background: #eee;
  text-align: left;
}

#external-events h4 {
  font-size: 16px;
  margin-top: 0;
  padding-top: 1em;
}

#external-events .fc-event {
  margin: 10px 0;
  cursor: pointer;
}

#external-events p {
  margin: 1.5em 0;
  font-size: 11px;
  color: #666;
}

#external-events p input {
  margin: 0;
  vertical-align: middle;
}

#calendar {
  float: right;
  width: 900px;
}
</style>
```

I can move my 'fc-events', but its can't drop on the full-calendar.

I include jQuery and jQueryUI in my 'nuxt.cofig.json' : 
```
head: {
    script: [
       { src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js' },
       {src: 'https://code.jquery.com/ui/1.12.1/jquery-ui.min.js' }
    ],
  }
```

And can't avoid it because if I disable jQuery I get a error while loadiing my page (on directives):
`ReferenceError: $ is not defined`

So. don't know what to do whith it.

**Comment by BrockReece** [comment]
@lbdlbdlbdl 

Thanks for reporting this, I have never used this component in a Nuxt project before, I will attempt to build an example app in the next couple of days and get back to you

**Comment by BrockReece** [comment]
https://github.com/BrockReece/vue-fullcalendar-nuxt

Maybe it would be best to move this issue to the new repo.

**Comment by SrPatinhas** [comment]
@BrockReece I'm having the same problem with the events, but i'm not using the nuxt (just pure vue) and i'm getting the same problem, I can drag the events, but the over (css on calendar) doesn't show anything neither the functions. I have the same code as this [Codepen](https://codepen.io/BrockReece/pen/LOPwyK?editors=0010) but it doesn't work. 
Help please?
