### ISSUE TITLE
Upgrade full calendar version ?

### ISSUE THREAD

**Issue by braimond-carelabs** [CroudSupport/vue-fullcalendar#73]
Hi,

Could you upgrade your package.json file to use the new version of full calendar ? Or maybe there is some incompatibilities with your Vue component ?

I need to use the new themeSystem option with bootstrap, wich has been included in 3.5.0, and I would like to keep your repository and not create a fork just for that.

Thanks

**Comment by BrockReece** [comment]
We found breaking changes between minor versions about two months ago, so I froze the version.
I would be happy to update the fullcalendar version though if these issues been addressed in later versions.

I will test and get back to you, if that is ok?

**Comment by BrockReece** [comment]
Could you test out that PR for me to make sure the changes will work for you and I will test from our end?

**Comment by braimond-carelabs** [comment]
Thank you very much for doing this so quickly ! I have checked with my app (basic usage of full calendar, with events like drag/drop, refresh events, goToDate, ... and everything works fine for me :)
You maybe should test advanced usage of it to be sure that everything is fine.

**Comment by BrockReece** [comment]
Thanks for testing it for me.

I may have to leave the testing to my colleague, @kingy04, he was the one who was finding the issues. He is away for the next couple of weeks though. I am happy to release a prerelease version on NPM though if you would find that useful?

**Comment by braimond-carelabs** [comment]
Yes it will be useful for me to have it from NPM.

Thanks.

**Comment by houseoftech** [comment]
I've been using latest FullCalendar (3.6.2) without any issues. There is an [incompatibility note on FullCalendar 3.5.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.5.0) about `clientEvents`.

> Event Objects obtained from clientEvents or various callbacks are no longer
references to internally used objects. Rather, they are static object copies.

Not sure if the change matters. It is also [only used](https://github.com/CroudSupport/vue-fullcalendar/blob/master/components/FullCalendar.vue#L87) if an undocumented `sync` prop is true (default is false).

**Comment by BrockReece** [comment]
Ok, thanks for that, as I said I will probably wait for my colleague to return rather than speculate on the error he received.

In the mean time, I will look at tagging a prerelease version on NPM so you guys can use that rather than a gitref.

**Comment by braimond-carelabs** [comment]
When think you this will be prereleased on NPM ?

Thanks !

**Comment by BrockReece** [comment]
Sorry I have just pre-released a new major version and tagged it with the `next` tag so you should be able to install this version using NPM or Yarn.
```bash
npm install vue-full-calendar@next --save
# or
yarn add vue-full-calendar@next
```

Standard installation should be unaffected

**Comment by braimond-carelabs** [comment]
Thanks, everything works fine.

**Comment by kingy04** [comment]
Hi All, the issues i was experiencing with fullcalendar 3.5 are fixed in 3.7 so we can go ahead and allow a later version of vue-full-calender.

Thanks, Antony

**Comment by BrockReece** [comment]
Cool, so as there aren't any breaking changes (from our point of view), I am tempted to only bump this up by a minor version revision, any objections?

**Comment by BrockReece** [comment]
Hi @jdriesen 
A bit off topic for this issue, but yes there is no reason why this wrapper can't be used with Scheduler. 

When I get more time I will build and test a working example (#79), but if you are feeling brave, I would probably go about it like this...

Download their package through [NPM](https://www.npmjs.com/package/fullcalendar-scheduler) and import this into your project
```js
import 'fullcalendar-scheduler'
```
Then you can add the required options to the config prop in vue-full-calendar
```html
<full-calendar :config="config" />
<script>
export default {
  data() {
    return {
      config: {
        defaultView: 'timelineMonth',
        events: [
          // events go here
        ],
        resources: [
          // resources go here
        ]
        // other options go here...
      },
    }
  },
}
</script>
```
