### ISSUE TITLE
Events mouseover and mouseout ?

### ISSUE THREAD

**Issue by braimond-carelabs** [CroudSupport/vue-fullcalendar#75]
Hi,

It seems that there is only eventRender, eventDestroy, eventClick, eventDrop, eventResize, dayClick and select events.

Is it possible to add mouseover and mouseout ? Or a generic method like fireMethod ?

Thank you for this great plugin !

**Comment by braimond-carelabs** [comment]
After testing it, this work perfectly :

```
eventMouseover(...args) {
    self.$emit('mouse-over', ...args)
},

eventMouseout(...args) {
    self.$emit('mouse-out', ...args)
},

**Comment by BrockReece** [comment]
You can also pass these options in as part of the config prop. This is a methodology that I would encourage as it mean's you won't have to rely on us to update this wrapper when things change on Fullcalendar.js

Happy to have a conversation about that though?

```js
// parent.vue
...
config: {
  eventMouseover(...args) {
    // handle the event in this component
  },

  eventMouseout(...args) {
    // handle the event in this component
  },
}

**Comment by BrockReece** [comment]
Oh and we do have a fire method that can be called from the parent component too.

```js
this.$refs.calendar.fireMethod('name', arg)
```

I have just realised this isn't in the docs though, I will add it soon.

**Comment by braimond-carelabs** [comment]
Ok thank you, this feature is really useful :)

I already had found the fireMethod in issues, but not the events in config object !

It will be really helpful for everybody in the doc.

Thanks for your quick answer.

**Comment by BrockReece** [comment]
Cool, I will look at adding these features to the readme.
Happy to help.
