### ISSUE TITLE
Add scheduler example

### ISSUE THREAD

**Issue by BrockReece** [CroudSupport/vue-fullcalendar#79]
Add a scheduler example to docs.
Seems like quite a popular question #69, #73

**Comment by BrockReece** [comment]
I think something like this would work... maybe someone using the package can confirm?

Download their package through NPM and import it into your project
```js
import 'fullcalendar-scheduler'
```

Then you can add the required options to the config prop in vue-full-calendar
```html
<full-calendar :config="config" />
<script>
export default {
  data() {
    return {
      config: {
        defaultView: 'timelineMonth',
        events: [
          // events go here
        ],
        resources: [
          // resources go here
        ]
        // other options go here...
      },
    }
  },
}
</script>
```

**Comment by BrockReece** [comment]
Here is a full working example of the code above
https://codesandbox.io/s/qlp8jvko3j

Does this work for everyone else?

**Comment by jdriesen** [comment]
Implemented in once of my test Apps, and works like a charm !
Thanks for your effort.

(during weekend, I'll test ALL features and params... will keep you informed.)

Kind regards & thanks again,
Johnny

**Comment by BrockReece** [comment]
Perfect, thanks 👍 
I'll add it to the docs when you are happy.

**Comment by BrockReece** [comment]
@jdriesen I have created a PR that links to this code sandbox. Let me know when you are happy and I will merge it in.

**Comment by jdriesen** [comment]
Ohhh... sorry ... my bad...
I think there is a misunderstanding here...

When I wrote... " I will do some tests during weekend", I was referring to MANUAL tests...
(like implementing and using the parameters...)

I don't have ANY experience is JEST or whatever... so I hope you're not waiting for me on this...

Grtz,
Johnny

**Comment by jdriesen** [comment]
I've just one remark (it's more like a question)

In calendar, Config and Events are seperate date props.
In Schedular... the Events are part of the config prop...

Any particular reason for this 'difference' ?
(Asking this just out of curiosity .. as mentioned before, I'm rather new to all this)

Grtz,
Johnny

**Comment by BrockReece** [comment]
Oh no sorry, I wasn't waiting for any formal tests, just wondering if you found any issues with the sandbox before I add it to the readme.

Good question, there is no real reason other than me copying the scheduler docs which had the events as part of the config options, you can pass in the events like that or as a prop. I will change that now though as it may cause undue confusion and distract from the important config options.

Thanks for your help with this.
