### ISSUE TITLE
Events listener not firing

### ISSUE THREAD

**Issue by xKairu** [CroudSupport/vue-fullcalendar#8]
```
events: {
    'event-selected'(event) {
      console.log(event);
    }
  },
```

This is in my component that wraps <full-calendar\> (Vue 1.0 version, 0.0.3), yet it never gets fired. The `event-selected` event is being dispatched as I can see using Vue devtools, which is why this isn't making any sense.

Am I dumb or is something wrong?

Edit: editable and selectable props don't seem to work either. I have to map my events to add the editable variable.

**Comment by BrockReece** [comment]
hi @xKairu

Hmm that is odd. I am using this event in production and never really had an issue with it.
Could you put your code in a gist or something and I will try it out?

Cheers
Brock

**Comment by xKairu** [comment]
JS component: https://gist.github.com/xKairu/2a1a76c08c529fe6bb5726283ca41a05

Template (Laravel Blade): https://gist.github.com/xKairu/a05c44ec2efe68a0f9e70a1991bc4286

Excuse the gross code, just hacked together to get it working at the moment.

**Comment by BrockReece** [comment]
Ok, that looks very similar to my code, I will test yours out after lunch though

**Comment by xKairu** [comment]
Yeah it's extremely straight forward and simple. Pull the events in and bind to the calendar component, which is why the event not listening caught me off guard.

**Comment by BrockReece** [comment]
I'm sorry, I'm really struggling to replicate your issue, I have tried quite a few permutations but it always fires the event and my parent components always pick it up.

The only way I can stop the events from firing is by adding the ' :selectable="false" ' prop to the full-calendar component.

**Comment by BrockReece** [comment]
What about the other events?
Does it catch 'event-drop' and 'event-resize'?

**Comment by xKairu** [comment]
I have no idea what happened, but it's working all of a sudden now. Thanks for the help.

**Comment by askz** [comment]
Hey same for me here. 

```
  events: {
    'event-selected'(event) {
      console.log(event);
    },
    'event-resize'(event) {
      console.log(event)
    }
  },```

Nothing happening. Even with vue debugger extension in chrome....
