### ISSUE TITLE
Click-Drag to create event not working

### ISSUE THREAD

**Issue by kjetilge** [CroudSupport/vue-fullcalendar#81]
I have a very simple component with fullcalendar: 
```
// Cal.vue
<template lang="html">
    <full-calendar></full-calendar>
</template>

<script>
export default {
}
</script>

<style lang="css">
 @import '~fullcalendar/dist/fullcalendar.css';
</style>
```

I have imported it to router and display it on http://localhost:8080/cal.

When I try to drag to create an event nothing happens.

However if I move the same component to the sample app found here:  https://github.com/BrockReece/vue-fullcalendar-example

and it works !

I suspected it had something todo with jquery so I copied this in to my apps webpack.base.conf.js from the sample app:

```
  plugins: [
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery"
    })
  ],
```

I've also tried to put this line inside main.js:

```
window.jQuery = window.$ = require('jquery')
```

– but still nothing happens when I click-drag in the calendar. All the other buttons work.

In my main.js I have
```
//...
import FullCalendar from 'vue-full-calendar';
//...
Vue.use(VueApollo)
Vue.use(VModal, { dialog: true })
Vue.use(VueLodash, lodash)
Vue.config.productionTip = false;
Vue.use(FullCalendar);
```

I'm unable to figure out any major difference between my app and the sample app – what could be the reason for this not working ?

**Comment by BrockReece** [comment]
Could the difference be that you are running it in a router? Could you try it outside of the `router-view`?

Have you ever used code sandbox, could you test it in that and send me a link to your project?

**Comment by kjetilge** [comment]
I just tried to now to import Cal.vue in to my App.vue and display it like this:
```
    <main class="main">
        <v-dialog/>
        <!--router-view></router-view-->
        <Cal />
    </main>
```
It's not working either.
By the way, why does your sample code not use: ```window.jQuery = window.$ = require('jquery')```  anywhere ?
I've never used code sandbox – I will try it now.

**Comment by BrockReece** [comment]
The webpack config you pointed out is doing the equivalent of `window.jQuery = window.$ = require('jquery')` but this shouldn't be needed because of changes we made earlier this week. The latest version handles the loading of jquery within the component.

**Comment by kjetilge** [comment]
That's great! – I'll try  code sandbox now and then I'll try out a fresh vue webpack project.

**Comment by BrockReece** [comment]
Cool, let me know.

**Comment by kjetilge** [comment]
It works fine on code sandbox: https://codesandbox.io/s/k5jwvmwlro
Now I'll try a fresh vue webpack project...

**Comment by kjetilge** [comment]
The first thing that hits me is this: ```Module build failed: Error: Couldn't find preset "es2015" relative to directory``` when trying to import FullCalendar.
All I have now is:
```
import Vue from 'vue'
import App from './App'
import FullCalendar from 'vue-full-calendar';

Vue.config.productionTip = false
Vue.use(FullCalendar);

new Vue({
  el: '#app',
  render: h => h(App)
})
```

**Comment by kjetilge** [comment]
had to: yarn add babel-preset-es2015
and then add { "presets": ["es2015"] } in  the .babelrc file in root folder to get past the es2015 issue

**Comment by kjetilge** [comment]
Also I could not just ```@import '~fullcalendar/dist/fullcalendar.css';``` inside the style tag so I copied everything from fullcalendar.css to the style tag. I guess I need som more configurations for that to work.

– But now it works in the fresh app! - so I guess I have a long debugging session ahead of me...

**Comment by kjetilge** [comment]
BareCSS was the culprit! As soon as I removed ```<link rel="stylesheet" type="text/css" href="/static/BareCSS/css/bare.min.css">``` from my html head I could drag-create events again.
I thought first the reason was related to z-index, but after experimenting with that, I'm not so shure. Only "solution" for the moment is to remove BareCss.

**Comment by BrockReece** [comment]
Hi @kjetilge 
Sorry for the delay, it has been a busy couple of days.

I have now removed babel-preset-es2015 in PR #83, if you would like to test it.
I have not used BareCss before, does it break your code sandbox too?

**Comment by BrockReece** [comment]
Hi @jiameng123 

Is this related to this issue? if not can we open a new issue with a bit more background info to keep things clean.
