### ISSUE TITLE
about Mouseover and Mouseout problem

### ISSUE THREAD

**Issue by adminlte** [CroudSupport/vue-fullcalendar#91]
Thank you for providing this plugin, it's very useful to me !!

i want to use `Mouseover` and `Mouseout` to change the event's color, the event may have many days, so i traverse the `cal.fullCalendar('clientEvents')` get `_id`  and `backgroundColor`, to change the  `events ` but demo has a deep watch events when it change ,the calendar remove all event ,at that time i blur the mouse event, `events` change again, it's just become a infinite loop

i change the `addEventSource`  to vue created but chrome warned me
 `fullcalendar.js?b577:650 Attempting to call a FullCalendar method on an element with no calendar.`

where can i use the `addEventSource`  or how to hover event to change color
please reply to me

**Comment by adminlte** [comment]
[mycode.txt](https://github.com/CroudSupport/vue-fullcalendar/files/1573982/mycode.txt)

**Comment by adminlte** [comment]
[mycode.txt](https://github.com/CroudSupport/vue-fullcalendar/files/1574020/mycode.txt)

**Comment by BrockReece** [comment]
Hi @adminlte 

Happy to help you work through this one.
However it doesn't look like you are using my component in the code you have included?
Are you trying to rewrite my Vue component?

**Comment by adminlte** [comment]
thank you relpy to me~
At first, i don't konw how to use the `vue-fullcalendar`  so ,i copy that code in [https://github.com/CroudSupport/vue-fullcalendar/blob/master/components/FullCalendar.vue](url) and make some changes, just now i fork the [https://github.com/BrockReece/vue-fullcalendar-example](url)
and change mycode to a vue component ,but i still dont' know how to use the `Mouseover` and `Mouseout` event ,beacuse when i use them it's still a infinite loop , where is my fault 0.0

**Comment by adminlte** [comment]
[mycode.txt](https://github.com/CroudSupport/vue-fullcalendar/files/1574983/mycode.txt)

**Comment by adminlte** [comment]
[mycode.txt](https://github.com/CroudSupport/vue-fullcalendar/files/1574983/mycode.txt)

**Comment by BrockReece** [comment]
With the greatest of respect, I would prefer to teach you how my component works rather than help you to fork my library.

The Vue component is a full wrapper for fullcalendar so it should be able to do anything you need without having to alter the underlying component.

The component accepts a `config` prop, which allows you to transparently send any config straight through to fullcalendar, so any changes that you have made to my Vue component can be affected from the parent.

Does that help?

Anyway, I am guessing what you need is something involving the [updateEvent](https://fullcalendar.io/docs/event_data/updateEvent/) method, and I think your config object would look something like this...

```js
{
  ...
  eventMouseover(event, jq, mouth) {
    event.backgroundColor = 'black'
    self.$refs.calendar.fireMethod('updateEvent', event)
  },
  eventMouseout (e) {
    event.backgroundColor = 'red'
    self.$refs.calendar.fireMethod('updateEvent', event)
  },
  ...
}
```

**Comment by adminlte** [comment]
Thank you provide me with `fireMethod`
![gif](https://user-images.githubusercontent.com/20222085/34203385-e220e998-e5b5-11e7-834b-1a957e0a91ee.gif)
I guess the component will be remove and reload when the data changed ,
how should I stop remove

**Comment by BrockReece** [comment]
I'm not sure sorry, I think this would be a question for the fullcalendar github page.
However, you could probably throttle/debounce the eventMouseover function?
