### ISSUE TITLE
How do you automatically bring in the start time and end time when dragging

### ISSUE THREAD

**Issue by Altamill** [CroudSupport/vue-fullcalendar#92]
I want to bring the start time and end time into my time component by clicking and dragging multiple time slots on the calendar.
I can print select start and end in Fullcalender. Vue, but I can't print out the value in my vue file.
```
//There's a value here
                    select(start, end, jsEvent, view, resource) {
                        console.log(start,end);
                        self.$emit('event-created', {
                            start,
                            end,
                            allDay: !start.hasTime() && !end.hasTime(),
                            view,
                            resource
                        });
                    }

//There's not a value here
                    eventCreated(dialogFormVisible, ...test) {
                      console.log('This is eventCreated!',this.start,this.end,this.allday);
```
How can I get the start and end values in the code below，thks！~

**Comment by BrockReece** [comment]
Sorry, just to clarify the console.log isn't printing out values for `this.start` etc?
Using the spread operator `...test` doesn't add the values to the `this` scope, I think you will find what you need by logging out the arguments passed into the method

```js
eventCreated(dialogFormVisible, ...test) {
  console.log(dialogFormVisible)
  console.log(test)
  // console.log('This is eventCreated!',this.start,this.end,this.allday);
}
```

Another thing to consider is the markup used in your template as it looks like you are expecting an arguement for `dialogFormVisible`. You need to make sure that you are also passing the event data through using `$event`  
```html
<full-calendar @event-created="eventCreated(true, $event)"/>
```

I hope this helps?

**Comment by Altamill** [comment]
Ok, I'll try

**Comment by Altamill** [comment]
I think this method should work. I'll try it. Because I used to say @events-created = "eventCreated".

**Comment by BrockReece** [comment]
That markup is fine and will transparently send through the event arguments, I was speculating based on the first argument that your method was expecting.

**Comment by Altamill** [comment]
I can already value it. Thanks~~~！୧(๑•̀◡•́๑)૭

**Comment by BrockReece** [comment]
Perfect. Glad to help
