### ISSUE TITLE
The docs currently do not describe how to load a new locale

### ISSUE THREAD

**Issue by TimonLukas** [CroudSupport/vue-fullcalendar#94]
Hey there! Great component. I am trying to use it in a project of mine, and got stuck for a few minutes on how to load a different locale. It is pretty simple, although it isn't really pretty in that the import triggers a side-effect - but I guess that just stems from the fact that FullCalendar wasn't really made to be used in an ES6-import-environment.

Anyways, you simply have to import it before the first calendar is used. This can happen in the script which initalizes the Vue instance, or even in the component which uses the calendar.

```javascript
import 'fullcalendar/dist/locale/de';
```

Like I said, really simple. But the docs should probably be updated to include this.

**Comment by BrockReece** [comment]
Good idea, I have answered a similar question a few times, I might even build a codesandbox for it.
Cheers :)

**Comment by BrockReece** [comment]
Could you double check that PR for me?

**Comment by TimonLukas** [comment]
The only thing I'd change is to specifically mention that you don't need the key if you only have a single language loaded, it works automatically just fine. Except for that it's great!

**Comment by BrockReece** [comment]
Thanks for the tip, this has been merged in now.
